<?php
final class SearchConsoleAnalytics {
    public static function importRows(PDO $pdo,array $rows,array $meta,int $userId): array {
        $from=(string)($meta['date_from']??'');$to=(string)($meta['date_to']??'');$source=trim((string)($meta['source_label']??'google_search_console_manual'));
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$from>$to)throw new InvalidArgumentException('invalid_date_range');
        if(!preg_match('/^[a-z0-9_\-]{2,80}$/i',$source))throw new InvalidArgumentException('invalid_source_label');
        $pdo->beginTransaction();
        try{
            $st=$pdo->prepare('INSERT INTO search_console_imports(source_label,property_uri,date_from,date_to,row_count,imported_by_user_id) VALUES(?,?,?,?,0,?)');
            $st->execute([$source,mb_substr(trim((string)($meta['property_uri']??'')),0,255)?:null,$from,$to,$userId]);$importId=(int)$pdo->lastInsertId();
            $ins=$pdo->prepare('INSERT INTO search_console_performance(import_id,metric_date,query_text,page_url,country_code,device_type,search_appearance,clicks,impressions,ctr,position) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
            $count=0;
            foreach($rows as $r){
                $date=(string)($r['date']??$r['metric_date']??'');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$date<$from||$date>$to)continue;
                $clicks=max(0,(float)($r['clicks']??0));$impr=max(0,(float)($r['impressions']??0));$ctr=array_key_exists('ctr',$r)?max(0,(float)$r['ctr']):($impr>0?$clicks/$impr:0);$pos=max(0,(float)($r['position']??0));
                $ins->execute([$importId,$date,mb_substr(trim((string)($r['query']??$r['query_text']??'')),0,700),mb_substr(trim((string)($r['page']??$r['page_url']??'')),0,1000),strtoupper(mb_substr(trim((string)($r['country']??$r['country_code']??'')),0,8)),strtolower(mb_substr(trim((string)($r['device']??$r['device_type']??'')),0,32)),mb_substr(trim((string)($r['search_appearance']??'')),0,120),$clicks,$impr,$ctr,$pos]);$count++;
            }
            $pdo->prepare('UPDATE search_console_imports SET row_count=? WHERE id=?')->execute([$count,$importId]);$pdo->commit();return ['import_id'=>$importId,'rows_imported'=>$count];
        }catch(Throwable $e){$pdo->rollBack();throw $e;}
    }

    public static function dashboard(PDO $pdo,string $from,string $to): array {
        if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||$from>$to)throw new InvalidArgumentException('invalid_date_range');
        $days=max(1,(int)((strtotime($to)-strtotime($from))/86400)+1);$prevTo=date('Y-m-d',strtotime($from.' -1 day'));$prevFrom=date('Y-m-d',strtotime($prevTo.' -'.($days-1).' days'));
        $current=self::summary($pdo,$from,$to);$previous=self::summary($pdo,$prevFrom,$prevTo);
        return ['range'=>['from'=>$from,'to'=>$to,'days'=>$days,'previous_from'=>$prevFrom,'previous_to'=>$prevTo],'summary'=>$current,'previous_summary'=>$previous,'daily'=>self::daily($pdo,$from,$to),'queries'=>self::dimension($pdo,'query_text',$from,$to,150),'pages'=>self::dimension($pdo,'page_url',$from,$to,150),'countries'=>self::dimension($pdo,'country_code',$from,$to,100),'devices'=>self::dimension($pdo,'device_type',$from,$to,20),'appearances'=>self::dimension($pdo,'search_appearance',$from,$to,50),'quick_wins'=>self::quickWins($pdo,$from,$to),'declining_pages'=>self::decliningPages($pdo,$from,$to,$prevFrom,$prevTo),'new_queries'=>self::newQueries($pdo,$from,$to,$prevFrom,$prevTo),'last_refresh'=>self::lastRefresh($pdo)];
    }

    private static function summary(PDO $pdo,string $from,string $to): array {
        $q=$pdo->prepare('SELECT COALESCE(SUM(clicks),0) clicks,COALESCE(SUM(impressions),0) impressions,CASE WHEN SUM(impressions)>0 THEN SUM(clicks)/SUM(impressions) ELSE 0 END ctr,CASE WHEN SUM(impressions)>0 THEN SUM(position*impressions)/SUM(impressions) ELSE 0 END position FROM search_console_performance WHERE metric_date BETWEEN ? AND ?');$q->execute([$from,$to]);return $q->fetch(PDO::FETCH_ASSOC)?:[];
    }
    private static function daily(PDO $pdo,string $from,string $to): array {$q=$pdo->prepare('SELECT metric_date date,SUM(clicks) clicks,SUM(impressions) impressions,CASE WHEN SUM(impressions)>0 THEN SUM(clicks)/SUM(impressions) ELSE 0 END ctr,CASE WHEN SUM(impressions)>0 THEN SUM(position*impressions)/SUM(impressions) ELSE 0 END position FROM search_console_performance WHERE metric_date BETWEEN ? AND ? GROUP BY metric_date ORDER BY metric_date');$q->execute([$from,$to]);return $q->fetchAll(PDO::FETCH_ASSOC);}
    private static function dimension(PDO $pdo,string $col,string $from,string $to,int $limit): array {if(!in_array($col,['query_text','page_url','country_code','device_type','search_appearance'],true))return [];$sql="SELECT $col dimension,SUM(clicks) clicks,SUM(impressions) impressions,CASE WHEN SUM(impressions)>0 THEN SUM(clicks)/SUM(impressions) ELSE 0 END ctr,CASE WHEN SUM(impressions)>0 THEN SUM(position*impressions)/SUM(impressions) ELSE 0 END position FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND $col<>'' GROUP BY $col ORDER BY impressions DESC LIMIT ".(int)$limit;$q=$pdo->prepare($sql);$q->execute([$from,$to]);return $q->fetchAll(PDO::FETCH_ASSOC);}
    private static function quickWins(PDO $pdo,string $from,string $to): array {$q=$pdo->prepare("SELECT query_text query,SUM(clicks) clicks,SUM(impressions) impressions,CASE WHEN SUM(impressions)>0 THEN SUM(clicks)/SUM(impressions) ELSE 0 END ctr,CASE WHEN SUM(impressions)>0 THEN SUM(position*impressions)/SUM(impressions) ELSE 0 END position FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND query_text<>'' GROUP BY query_text HAVING impressions>=20 AND position BETWEEN 11 AND 30 ORDER BY impressions DESC LIMIT 100");$q->execute([$from,$to]);return $q->fetchAll(PDO::FETCH_ASSOC);}
    private static function decliningPages(PDO $pdo,string $from,string $to,string $pf,string $pt): array {$sql="SELECT c.page_url page,c.impressions current_impressions,COALESCE(p.impressions,0) previous_impressions,c.clicks current_clicks,COALESCE(p.clicks,0) previous_clicks FROM (SELECT page_url,SUM(impressions) impressions,SUM(clicks) clicks FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND page_url<>'' GROUP BY page_url)c LEFT JOIN (SELECT page_url,SUM(impressions) impressions,SUM(clicks) clicks FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND page_url<>'' GROUP BY page_url)p ON p.page_url=c.page_url WHERE p.impressions IS NOT NULL AND c.impressions<p.impressions ORDER BY (p.impressions-c.impressions) DESC LIMIT 100";$q=$pdo->prepare($sql);$q->execute([$from,$to,$pf,$pt]);return $q->fetchAll(PDO::FETCH_ASSOC);}
    private static function newQueries(PDO $pdo,string $from,string $to,string $pf,string $pt): array {$sql="SELECT c.query_text query,c.impressions,c.clicks FROM (SELECT query_text,SUM(impressions) impressions,SUM(clicks) clicks FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND query_text<>'' GROUP BY query_text)c LEFT JOIN (SELECT DISTINCT query_text FROM search_console_performance WHERE metric_date BETWEEN ? AND ? AND query_text<>'')p ON p.query_text=c.query_text WHERE p.query_text IS NULL ORDER BY c.impressions DESC LIMIT 100";$q=$pdo->prepare($sql);$q->execute([$from,$to,$pf,$pt]);return $q->fetchAll(PDO::FETCH_ASSOC);}
    private static function lastRefresh(PDO $pdo):?array {$r=$pdo->query('SELECT source_label,property_uri,date_from,date_to,row_count,imported_at FROM search_console_imports ORDER BY imported_at DESC,id DESC LIMIT 1')->fetch(PDO::FETCH_ASSOC);return $r?:null;}
}