<?php
final class Security {
  public static function start(): void { if(session_status()!==PHP_SESSION_ACTIVE){session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS']),'samesite'=>'Lax','path'=>'/']);session_start();} header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header("Content-Security-Policy: default-src 'self'; connect-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'"); }
  public static function csrf(): string { self::start(); if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24)); return $_SESSION['csrf']; }
  public static function requireCsrf(): void { self::start(); $got=$_SERVER['HTTP_X_CSRF_TOKEN']??''; if(!$got||!hash_equals($_SESSION['csrf']??'', $got)){http_response_code(403);header('Content-Type: application/json');echo json_encode(['error'=>'csrf_failed']);exit;} }
  public static function sameOrigin(array $config): void { $origin=$_SERVER['HTTP_ORIGIN']??''; if($origin && rtrim($origin,'/')!==rtrim($config['site_url'],'/')){http_response_code(403);header('Content-Type: application/json');echo json_encode(['error'=>'origin_rejected']);exit;} }
  public static function rateLimit(PDO $pdo,string $route,int $limit=30,int $seconds=60): void { $ip=$_SERVER['REMOTE_ADDR']??'unknown';$bucket=hash('sha256',$ip,true);$start=date('Y-m-d H:i:00',time()-time()%$seconds);$pdo->prepare("INSERT INTO rate_limits(bucket_key,route_key,window_start,hit_count) VALUES(?,?,?,1) ON DUPLICATE KEY UPDATE hit_count=hit_count+1")->execute([$bucket,$route,$start]);$st=$pdo->prepare("SELECT hit_count FROM rate_limits WHERE bucket_key=? AND route_key=? AND window_start=?");$st->execute([$bucket,$route,$start]);if((int)$st->fetchColumn()>$limit){http_response_code(429);header('Retry-After: '.$seconds);header('Content-Type: application/json');echo json_encode(['error'=>'rate_limited']);exit;} }
  public static function user(): ?array { self::start(); return $_SESSION['user']??null; }
  public static function requireRole(array $roles): array { $u=self::user(); if(!$u){http_response_code(401);header('Content-Type: application/json');echo json_encode(['error'=>'authentication_required']);exit;} if(!in_array($u['role'],$roles,true)){http_response_code(403);header('Content-Type: application/json');echo json_encode(['error'=>'forbidden']);exit;} return $u; }
  public static function audit(PDO $pdo,?int $uid,string $action,string $type,?string $id=null,$before=null,$after=null): void { $ip=hash('sha256',$_SERVER['REMOTE_ADDR']??'',true);$pdo->prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,before_json,after_json,ip_hash) VALUES(?,?,?,?,?,?,?)")->execute([$uid,$action,$type,$id,$before===null?null:json_encode($before),$after===null?null:json_encode($after),$ip]); }
}
