<?php
final class SelectionProjects {
  private const STATUSES=['draft','active','shortlisting','decision_ready','archived'];
  private const SOURCES=['user_entered','ai_suggested','inferred'];
  private const PRIORITIES=['mandatory','important','preferred'];

  public static function list(PDO $pdo,int $userId):array{
    $st=$pdo->prepare("SELECT id,name,status,company_size_band,industry_text,expected_users,implementation_timeline,updated_at FROM selection_projects WHERE user_id=? ORDER BY updated_at DESC LIMIT 100");
    $st->execute([$userId]);return $st->fetchAll();
  }

  public static function get(PDO $pdo,int $userId,int $id):array{
    $st=$pdo->prepare("SELECT * FROM selection_projects WHERE id=? AND user_id=? LIMIT 1");$st->execute([$id,$userId]);$p=$st->fetch();if(!$p)throw new RuntimeException('not_found');
    foreach(['country_codes_json','current_systems_json','security_compliance_json'] as $k)$p[$k]=self::decode($p[$k]??null);
    $r=$pdo->prepare("SELECT r.*,c.name capability_name,c.slug capability_slug FROM selection_project_requirements r LEFT JOIN capabilities c ON c.id=r.capability_id WHERE r.project_id=? ORDER BY r.is_mandatory DESC,FIELD(r.priority,'mandatory','important','preferred'),r.id");$r->execute([$id]);$p['requirements']=$r->fetchAll();
    $i=$pdo->prepare("SELECT i.*,x.name integration_catalog_name,x.slug integration_slug FROM selection_project_integrations i LEFT JOIN integrations x ON x.id=i.integration_id WHERE i.project_id=? ORDER BY i.is_mandatory DESC,FIELD(i.priority,'mandatory','important','preferred'),i.id");$i->execute([$id]);$p['integrations']=$i->fetchAll();
    $p['requirements_brief']=self::brief($p);return $p;
  }

  public static function create(PDO $pdo,int $userId,array $b):array{
    $name=self::text($b['name']??'',255,true);$consultationId=self::ownedConsultationId($pdo,$userId,$b['consultation_id']??null);
    $base=self::fields($b);if($consultationId){$base=self::mergeConsultation($pdo,$userId,$consultationId,$base);}
    $sql="INSERT INTO selection_projects(user_id,consultation_id,name,status,company_size_band,industry_text,country_codes_json,expected_users,current_systems_json,deployment_preference,security_compliance_json,budget_min,budget_max,budget_currency,budget_period,implementation_capacity,implementation_timeline,support_requirements,strategic_objectives) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    $pdo->prepare($sql)->execute([$userId,$consultationId,$name,$base['status'],$base['company_size_band'],$base['industry_text'],json_encode($base['country_codes'],JSON_UNESCAPED_SLASHES),$base['expected_users'],json_encode($base['current_systems'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$base['deployment_preference'],json_encode($base['security_compliance'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$base['budget_min'],$base['budget_max'],$base['budget_currency'],$base['budget_period'],$base['implementation_capacity'],$base['implementation_timeline'],$base['support_requirements'],$base['strategic_objectives']]);
    $id=(int)$pdo->lastInsertId();
    if($consultationId)self::importConsultationRequirements($pdo,$id,$userId,$consultationId);
    return self::get($pdo,$userId,$id);
  }

  public static function update(PDO $pdo,int $userId,int $id,array $b):array{
    $current=self::get($pdo,$userId,$id);$merged=[];foreach(['status','company_size_band','industry_text','expected_users','deployment_preference','budget_min','budget_max','budget_currency','budget_period','implementation_capacity','implementation_timeline','support_requirements','strategic_objectives'] as $k)$merged[$k]=array_key_exists($k,$b)?$b[$k]:($current[$k]??null);
    $merged['country_codes']=array_key_exists('country_codes',$b)?$b['country_codes']:$current['country_codes_json'];$merged['current_systems']=array_key_exists('current_systems',$b)?$b['current_systems']:$current['current_systems_json'];$merged['security_compliance']=array_key_exists('security_compliance',$b)?$b['security_compliance']:$current['security_compliance_json'];$f=self::fields($merged);$name=array_key_exists('name',$b)?self::text($b['name'],255,true):$current['name'];
    $pdo->prepare("UPDATE selection_projects SET name=?,status=?,company_size_band=?,industry_text=?,country_codes_json=?,expected_users=?,current_systems_json=?,deployment_preference=?,security_compliance_json=?,budget_min=?,budget_max=?,budget_currency=?,budget_period=?,implementation_capacity=?,implementation_timeline=?,support_requirements=?,strategic_objectives=?,version=version+1,updated_at=NOW() WHERE id=? AND user_id=?")->execute([$name,$f['status'],$f['company_size_band'],$f['industry_text'],json_encode($f['country_codes'],JSON_UNESCAPED_SLASHES),$f['expected_users'],json_encode($f['current_systems'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$f['deployment_preference'],json_encode($f['security_compliance'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$f['budget_min'],$f['budget_max'],$f['budget_currency'],$f['budget_period'],$f['implementation_capacity'],$f['implementation_timeline'],$f['support_requirements'],$f['strategic_objectives'],$id,$userId]);
    return self::get($pdo,$userId,$id);
  }

  public static function addRequirement(PDO $pdo,int $userId,int $projectId,array $b):array{
    self::get($pdo,$userId,$projectId);$text=self::text($b['requirement_text']??'',2000,true);$source=self::source($b['source']??'user_entered');$priority=self::priority($b['priority']??(!empty($b['is_mandatory'])?'mandatory':'preferred'));$mandatory=!empty($b['is_mandatory'])||$priority==='mandatory';$confirmed=array_key_exists('user_confirmed',$b)?!empty($b['user_confirmed']):$source==='user_entered';$cap=self::nullablePositive($b['capability_id']??null);
    $pdo->prepare("INSERT INTO selection_project_requirements(project_id,capability_id,requirement_text,normalized_requirement,priority,is_mandatory,source,user_confirmed,confidence_score) VALUES(?,?,?,?,?,?,?,?,?)")->execute([$projectId,$cap,$text,self::text($b['normalized_requirement']??'',2000,false),$priority,$mandatory?1:0,$source,$confirmed?1:0,self::confidence($b['confidence_score']??null)]);
    return self::get($pdo,$userId,$projectId);
  }

  public static function addIntegration(PDO $pdo,int $userId,int $projectId,array $b):array{
    self::get($pdo,$userId,$projectId);$name=self::text($b['integration_name']??'',190,true);$source=self::source($b['source']??'user_entered');$priority=self::priority($b['priority']??(!empty($b['is_mandatory'])?'mandatory':'preferred'));$mandatory=!empty($b['is_mandatory'])||$priority==='mandatory';$confirmed=array_key_exists('user_confirmed',$b)?!empty($b['user_confirmed']):$source==='user_entered';$integration=self::nullablePositive($b['integration_id']??null);
    $pdo->prepare("INSERT INTO selection_project_integrations(project_id,integration_id,integration_name,priority,is_mandatory,source,user_confirmed,notes) VALUES(?,?,?,?,?,?,?,?)")->execute([$projectId,$integration,$name,$priority,$mandatory?1:0,$source,$confirmed?1:0,self::text($b['notes']??'',2000,false)]);return self::get($pdo,$userId,$projectId);
  }

  public static function deleteChild(PDO $pdo,int $userId,int $projectId,string $kind,int $childId):array{
    self::get($pdo,$userId,$projectId);$table=$kind==='requirement'?'selection_project_requirements':($kind==='integration'?'selection_project_integrations':null);if(!$table)throw new InvalidArgumentException('invalid_child_type');$pdo->prepare("DELETE FROM {$table} WHERE id=? AND project_id=?")->execute([$childId,$projectId]);return self::get($pdo,$userId,$projectId);
  }

  private static function fields(array $b):array{
    $status=(string)($b['status']??'draft');if(!in_array($status,self::STATUSES,true))$status='draft';$min=self::money($b['budget_min']??null);$max=self::money($b['budget_max']??null);if($min!==null&&$max!==null&&$max<$min)throw new InvalidArgumentException('invalid_budget_range');
    return ['status'=>$status,'company_size_band'=>self::text($b['company_size_band']??'',64,false),'industry_text'=>self::text($b['industry_text']??'',190,false),'country_codes'=>self::countries($b['country_codes']??[]),'expected_users'=>self::nullablePositive($b['expected_users']??null),'current_systems'=>self::stringList($b['current_systems']??[]),'deployment_preference'=>self::text($b['deployment_preference']??'',100,false),'security_compliance'=>self::stringList($b['security_compliance']??[]),'budget_min'=>$min,'budget_max'=>$max,'budget_currency'=>self::currency($b['budget_currency']??null),'budget_period'=>self::text($b['budget_period']??'',50,false),'implementation_capacity'=>self::text($b['implementation_capacity']??'',100,false),'implementation_timeline'=>self::text($b['implementation_timeline']??'',100,false),'support_requirements'=>self::text($b['support_requirements']??'',4000,false),'strategic_objectives'=>self::text($b['strategic_objectives']??'',4000,false)];
  }

  private static function mergeConsultation(PDO $pdo,int $userId,int $id,array $base):array{$st=$pdo->prepare("SELECT business_problem,country_code,company_size_band,expected_users,budget_min,budget_max,budget_currency,budget_period,implementation_timeline,preferred_deployment FROM consultations WHERE id=? AND user_id=? LIMIT 1");$st->execute([$id,$userId]);$c=$st->fetch();if(!$c)return $base;if(!$base['strategic_objectives'])$base['strategic_objectives']=$c['business_problem'];if(!$base['country_codes']&&!empty($c['country_code']))$base['country_codes']=[strtoupper($c['country_code'])];foreach(['company_size_band','expected_users','budget_min','budget_max','budget_currency','budget_period','implementation_timeline'] as $k)if(empty($base[$k])&&!empty($c[$k]))$base[$k]=$c[$k];if(!$base['deployment_preference']&&!empty($c['preferred_deployment']))$base['deployment_preference']=$c['preferred_deployment'];return $base;}
  private static function importConsultationRequirements(PDO $pdo,int $projectId,int $userId,int $consultationId):void{$st=$pdo->prepare("SELECT capability_id,requirement_text,normalized_requirement,priority,is_mandatory,source,confidence_score,user_confirmed FROM consultation_requirements WHERE consultation_id=?");$st->execute([$consultationId]);$ins=$pdo->prepare("INSERT INTO selection_project_requirements(project_id,capability_id,requirement_text,normalized_requirement,priority,is_mandatory,source,user_confirmed,confidence_score) VALUES(?,?,?,?,?,?,?,?,?)");foreach($st->fetchAll() as $r){$source=($r['source']??'')==='user_added'?'user_entered':(($r['source']??'')==='ai_inferred'?'inferred':'ai_suggested');$priority=!empty($r['is_mandatory'])?'mandatory':(in_array($r['priority']??'',['important','preferred'],true)?$r['priority']:'preferred');$ins->execute([$projectId,$r['capability_id'],$r['requirement_text'],$r['normalized_requirement'],$priority,(int)$r['is_mandatory'],$source,(int)$r['user_confirmed'],$r['confidence_score']]);}}
  private static function ownedConsultationId(PDO $pdo,int $userId,$v):?int{$id=self::nullablePositive($v);if(!$id)return null;$st=$pdo->prepare("SELECT id FROM consultations WHERE id=? AND user_id=? LIMIT 1");$st->execute([$id,$userId]);if(!$st->fetchColumn())throw new InvalidArgumentException('invalid_consultation');return $id;}
  private static function brief(array $p):array{return ['project_name'=>$p['name'],'business_context'=>['company_size'=>$p['company_size_band'],'industry'=>$p['industry_text'],'countries'=>$p['country_codes_json'],'expected_users'=>$p['expected_users'],'current_systems'=>$p['current_systems_json']],'constraints'=>['deployment'=>$p['deployment_preference'],'security_compliance'=>$p['security_compliance_json'],'budget'=>['min'=>$p['budget_min'],'max'=>$p['budget_max'],'currency'=>$p['budget_currency'],'period'=>$p['budget_period']],'implementation_capacity'=>$p['implementation_capacity'],'timeline'=>$p['implementation_timeline'],'support'=>$p['support_requirements']],'strategic_objectives'=>$p['strategic_objectives'],'requirements'=>array_map(fn($r)=>['text'=>$r['requirement_text'],'priority'=>$r['priority'],'mandatory'=>(bool)$r['is_mandatory'],'source'=>$r['source'],'confirmed'=>(bool)$r['user_confirmed']],$p['requirements']),'integrations'=>array_map(fn($r)=>['name'=>$r['integration_name'],'priority'=>$r['priority'],'mandatory'=>(bool)$r['is_mandatory'],'source'=>$r['source'],'confirmed'=>(bool)$r['user_confirmed']],$p['integrations'])];}
  private static function source($v):string{$v=(string)$v;if(!in_array($v,self::SOURCES,true))throw new InvalidArgumentException('invalid_source');return $v;}private static function priority($v):string{$v=(string)$v;if(!in_array($v,self::PRIORITIES,true))throw new InvalidArgumentException('invalid_priority');return $v;}
  private static function text($v,int $max,bool $required):?string{$v=trim((string)$v);if($required&&$v==='')throw new InvalidArgumentException('required_field');if($v==='')return null;return mb_substr($v,0,$max);}private static function nullablePositive($v):?int{$n=(int)$v;return $n>0?$n:null;}private static function money($v):?float{if($v===null||$v==='')return null;if(!is_numeric($v)||$v<0)throw new InvalidArgumentException('invalid_money');return round((float)$v,2);}private static function currency($v):?string{$v=strtoupper(trim((string)$v));return preg_match('/^[A-Z]{3}$/',$v)?$v:null;}private static function confidence($v):?float{if($v===null||$v==='')return null;$n=(float)$v;return max(0,min(1,$n));}
  private static function countries($v):array{$a=is_array($v)?$v:preg_split('/[,\s]+/',(string)$v,-1,PREG_SPLIT_NO_EMPTY);$out=[];foreach($a as $x){$x=strtoupper(trim((string)$x));if(preg_match('/^[A-Z]{2}$/',$x))$out[]=$x;}return array_values(array_unique($out));}private static function stringList($v):array{$a=is_array($v)?$v:preg_split('/\r?\n|,/',(string)$v,-1,PREG_SPLIT_NO_EMPTY);$out=[];foreach($a as $x){$x=trim((string)$x);if($x!=='')$out[]=mb_substr($x,0,255);}return array_values(array_unique($out));}private static function decode($v):array{$d=$v?json_decode($v,true):[];return is_array($d)?$d:[];}
}
