<?php
require_once __DIR__.'/app/lib/Db.php';
require_once __DIR__.'/app/lib/Security.php';
require_once __DIR__.'/app/lib/AuthoritySources.php';
Security::start();Security::requireRole(['admin','super_admin','data_editor']);$pdo=Db::pdo();$days=max(1,min(365,(int)($_GET['days']??30)));
$summary=['total'=>0,'prospects'=>0,'contacted'=>0,'published'=>0,'active_backlinks'=>0,'lost_backlinks'=>0,'by_type'=>[]];$sources=[];try{$summary=AuthoritySources::summary($pdo);$sources=AuthoritySources::list($pdo);}catch(Throwable $e){}
$st=$pdo->prepare("SELECT utm_source,utm_medium,utm_campaign,referrer,COUNT(*) visits FROM visitor_sessions WHERE first_seen_at>=DATE_SUB(NOW(),INTERVAL ? DAY) AND (utm_source IS NOT NULL OR referrer IS NOT NULL) GROUP BY utm_source,utm_medium,utm_campaign,referrer ORDER BY visits DESC LIMIT 100");$st->execute([$days]);$refs=[];$domains=[];
foreach($st->fetchAll()?:[] as $r){$host='';if(!empty($r['referrer']))$host=strtolower((string)parse_url($r['referrer'],PHP_URL_HOST));if($host==='techselectai.com'||$host==='www.techselectai.com')$host='';$key=$host?:((string)($r['utm_source']??'direct/utm'));$domains[$key]=($domains[$key]??0)+(int)$r['visits'];$refs[]=$r;}
arsort($domains);function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Authority Analytics | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#f7f9fc;color:#172033}.wrap{max-width:1180px;margin:32px auto;padding:0 20px}.metrics,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.metric,.panel{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:16px}.metric strong{font-size:28px;color:#1A365D}.metric span{display:block;color:#64748b;font-size:12px}.panel{margin-top:18px}.row{display:flex;justify-content:space-between;gap:16px;padding:9px 0;border-bottom:1px solid #edf2f7}.row:last-child{border:0}.muted{color:#64748b;font-size:13px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #edf2f7;font-size:13px}</style></head><body><main class="wrap"><h1>External Authority & Referral Analytics</h1><p class="muted">Tracks only first-party outreach status and aggregate referral metadata. A source is not counted as an active backlink unless a published URL has been recorded and verified.</p><div class="metrics"><div class="metric"><strong><?=h($summary['total'])?></strong><span>Tracked sources</span></div><div class="metric"><strong><?=h($summary['active_backlinks'])?></strong><span>Verified active backlinks</span></div><div class="metric"><strong><?=h($summary['contacted'])?></strong><span>Contacted / follow-up</span></div><div class="metric"><strong><?=h($summary['published'])?></strong><span>Published mentions</span></div></div><section class="panel"><h2>Referral sources — last <?=h($days)?> days</h2><?php if(!$domains):?><p class="muted">No tagged/external referral data yet.</p><?php else: foreach($domains as $domain=>$count):?><div class="row"><span><?=h($domain)?></span><strong><?=h($count)?></strong></div><?php endforeach; endif;?></section><section class="panel"><h2>Authority source pipeline</h2><?php if(!$sources):?><p class="muted">No authority prospects recorded yet. Add only real directories, publications, partners, customers or vendor references—never fabricated links.</p><?php else:?><table><thead><tr><th>Source</th><th>Type</th><th>Status</th><th>Backlink</th><th>Next action</th></tr></thead><tbody><?php foreach($sources as $s):?><tr><td><?=h($s['source_name'])?><br><span class="muted"><?=h($s['domain'])?></span></td><td><?=h($s['source_type'])?></td><td><?=h($s['outreach_status'])?></td><td><?=h($s['backlink_status'])?></td><td><?=h($s['next_action']??'')?></td></tr><?php endforeach;?></tbody></table><?php endif;?></section></main></body></html>
