<?php
require_once __DIR__.'/app/lib/Db.php';
require_once __DIR__.'/app/lib/Security.php';
require_once __DIR__.'/app/lib/AuthorityReferralAnalytics.php';
require_once __DIR__.'/app/lib/AuthoritySources.php';
Security::start();Security::requireRole(['reviewer','admin','super_admin']);$pdo=Db::pdo();$days=max(1,min(365,(int)($_GET['days']??30)));
$ref=['days'=>$days,'external_or_tagged_sessions'=>0,'by_category'=>[],'top_sources'=>[]];$pipeline=['total'=>0,'prospects'=>0,'contacted'=>0,'published'=>0,'active_backlinks'=>0,'lost_backlinks'=>0,'by_type'=>[]];try{$ref=AuthorityReferralAnalytics::summary($pdo,$days);}catch(Throwable $e){}try{$pipeline=AuthoritySources::summary($pdo);}catch(Throwable $e){}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Authority & Referral Analytics | TechSelectAI</title><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#f7f9fc;color:#172033}.wrap{max-width:1180px;margin:32px auto;padding:0 20px}.metrics,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.metric,.panel{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:16px}.metric strong{font-size:28px;color:#1A365D}.metric span{display:block;color:#64748b;font-size:12px}.panel{margin-top:18px}.row{display:flex;justify-content:space-between;gap:16px;padding:9px 0;border-bottom:1px solid #edf2f7}.row:last-child{border:0}.muted{color:#64748b;font-size:13px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #edf2f7;font-size:13px}.filters a{margin-right:10px}</style></head><body><main class="wrap"><p><a href="/authority-admin">← Authority tracker</a></p><h1>External Authority & Referral Analytics</h1><p class="muted">First-party referral measurement only. Referrer query strings and fragments are not stored. Categories are conservative and may remain “other” when the source cannot be verified.</p><div class="filters"><a href="?days=7">7 days</a><a href="?days=30">30 days</a><a href="?days=90">90 days</a></div><div class="metrics"><div class="metric"><strong><?=h($ref['external_or_tagged_sessions'])?></strong><span>External or tagged consultation sessions</span></div><div class="metric"><strong><?=h($pipeline['active_backlinks'])?></strong><span>Verified active backlinks</span></div><div class="metric"><strong><?=h($pipeline['contacted'])?></strong><span>Contacted / follow-up</span></div><div class="metric"><strong><?=h($pipeline['published'])?></strong><span>Published mentions</span></div></div><section class="panel"><h2>Referral categories — last <?=h($days)?> days</h2><?php if(empty($ref['by_category'])):?><p class="muted">No external/tagged consultation referrals recorded yet.</p><?php else:foreach($ref['by_category'] as $category=>$count):?><div class="row"><span><?=h($category)?></span><strong><?=h($count)?></strong></div><?php endforeach;endif;?></section><section class="panel"><h2>Top referral sources</h2><?php if(empty($ref['top_sources'])):?><p class="muted">No source-level referral data yet.</p><?php else:?><table><thead><tr><th>Source</th><th>Category</th><th>Consultation sessions</th></tr></thead><tbody><?php foreach($ref['top_sources'] as $r):?><tr><td><?=h($r['source'])?></td><td><?=h($r['category'])?></td><td><?=h($r['visits'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></section></main></body></html>
