<?php
$product=preg_replace('/[^a-z0-9-]/','',strtolower((string)($_GET['product']??'')));
$consultation=max(0,(int)($_GET['consultation']??0));
if($product===''){http_response_code(400);exit('Product is required');}
$next='/build-business-case?product='.rawurlencode($product).($consultation>0?'&consultation='.$consultation:'');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Build a Business Case | TechSelectAI</title><link rel="icon" type="image/svg+xml" href="/favicon.svg"><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#f7f9fc;color:#172033}.wrap{max-width:760px;margin:48px auto;padding:0 20px}.brand img{height:38px;width:auto}.card{margin-top:28px;background:#fff;border:1px solid #dbe5ee;border-radius:18px;padding:26px;box-shadow:0 12px 34px rgba(15,23,42,.07)}h1{margin:0 0 10px;font-size:32px}.muted{color:#64748b;line-height:1.6}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 16px;border-radius:10px;text-decoration:none;font-weight:750;border:1px solid #cbd5e1;background:#fff;color:#123b67;cursor:pointer}.primary{background:#123b67;color:#fff;border-color:#123b67}.status{margin-top:14px;color:#64748b}.err{color:#b91c1c}@media(max-width:560px){.actions .btn{flex:1 1 160px}}</style></head><body><main class="wrap"><a class="brand" href="/"><img src="/techselectai-logo.svg" alt="TechSelectAI"></a><section class="card"><p class="muted">AI Business Case Builder</p><h1>Build a Business Case</h1><p class="muted">Turn this recommendation into a management-ready justification. TechSelectAI will reuse known consultation context and clearly separate verified product facts from your assumptions and AI-generated estimates.</p><div id="app"><p class="status">Checking your account…</p></div></section></main><script>
const product=<?=json_encode($product)?>,consultation=<?=json_encode($consultation)?>,next=<?=json_encode($next)?>,app=document.getElementById('app');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function json(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.message||'Request failed');return d}
async function init(){try{const auth=await json('/api/auth/csrf');if(!auth.user){const q=encodeURIComponent(next);app.innerHTML=`<p class="muted">Create a free account or sign in to save and edit this business case.</p><div class="actions"><a class="btn primary" href="/register?next=${q}">Create account</a><a class="btn" href="/login?next=${q}">Log in</a></div>`;return}const data=await json('/api/software/'+encodeURIComponent(product));const p=data.product;if(!p?.id)throw new Error('Product unavailable');app.innerHTML=`<p class="muted">Selected product: <b>${esc(p.name)}</b></p><div class="actions"><button id="create" class="btn primary">Create Business Case</button><a class="btn" href="/software/${encodeURIComponent(product)}">Back to product</a></div><p id="status" class="status"></p>`;document.getElementById('create').onclick=async e=>{const b=e.currentTarget;b.disabled=true;document.getElementById('status').textContent='Preparing your business case…';try{const created=await json('/api/business-cases',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':auth.csrf_token||''},body:JSON.stringify({product_id:Number(p.id),consultation_id:consultation||0})});location.href='/business-case?id='+encodeURIComponent(created.id)}catch(err){b.disabled=false;const s=document.getElementById('status');s.className='status err';s.textContent=err.message}}}catch(err){app.innerHTML='<p class="status err">'+esc(err.message)+'</p><div class="actions"><a class="btn" href="/">Return to TechSelectAI</a></div>'}}
init();
</script></body></html>