<?php
$product=preg_replace('/[^a-z0-9-]/','',strtolower((string)($_GET['product']??'')));
$consultation=max(0,(int)($_GET['consultation']??0));
if($product===''){http_response_code(400);exit('Product is required');}
$next='/build-business-case?product='.rawurlencode($product).($consultation>0?'&consultation='.$consultation:'');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Build a Business Case | TechSelectAI</title><link rel="icon" type="image/svg+xml" href="/favicon.svg"><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#f7f9fc;color:#172033}.wrap{max-width:860px;margin:48px auto;padding:0 20px}.brand img{height:38px;width:auto}.card{margin-top:28px;background:#fff;border:1px solid #dbe5ee;border-radius:18px;padding:26px;box-shadow:0 12px 34px rgba(15,23,42,.07)}h1{margin:0 0 10px;font-size:32px}.muted{color:#64748b;line-height:1.6}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 16px;border-radius:10px;text-decoration:none;font-weight:750;border:1px solid #cbd5e1;background:#fff;color:#123b67;cursor:pointer}.primary{background:#123b67;color:#fff;border-color:#123b67}.status{margin-top:14px;color:#64748b}.err{color:#b91c1c}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.field label{display:block;font-weight:700;font-size:13px;margin-bottom:5px}.field textarea{width:100%;min-height:86px;box-sizing:border-box;padding:10px 11px;border:1px solid #cbd5e1;border-radius:10px;font:inherit;resize:vertical}.preview{margin-top:22px;border-top:1px solid #e2e8f0;padding-top:20px}.preview section{margin:0 0 18px}.preview h3{margin:0 0 6px;font-size:17px}.preview p{margin:0;line-height:1.65;color:#334155}.badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#eef6fa;color:#123b67;font-size:12px;font-weight:700}@media(max-width:680px){.form-grid{grid-template-columns:1fr}.actions .btn{flex:1 1 160px}}</style></head><body><main class="wrap"><a class="brand" href="/"><img src="/techselectai-logo.svg" alt="TechSelectAI"></a><section class="card"><p class="muted">AI Business Case Builder</p><h1>Build a Business Case</h1><p class="muted">Turn this recommendation into a management-ready justification. TechSelectAI reuses known consultation context and keeps verified product facts separate from your assumptions and AI-generated estimates.</p><div id="app"><p class="status">Preparing the builder…</p></div></section></main><script>
const product=<?=json_encode($product)?>,consultation=<?=json_encode($consultation)?>,next=<?=json_encode($next)?>,app=document.getElementById('app');
const ACTIVE='techselectai.activeConsultation.v1',DRAFT='techselectai.businessCaseDraft.v1';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function json(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}
function activeConsultation(){try{return JSON.parse(sessionStorage.getItem(ACTIVE)||'null')}catch{return null}}
function draft(){try{const d=JSON.parse(sessionStorage.getItem(DRAFT)||'null');return d?.product===product?d.assumptions||{}:{}}catch{return{}}}
function values(){const o={};document.querySelectorAll('[data-assumption]').forEach(el=>{const v=el.value.trim();if(v)o[el.dataset.assumption]=v});return o}
function saveDraft(v){try{sessionStorage.setItem(DRAFT,JSON.stringify({product,assumptions:v}))}catch{}}
function fields(v={}){const defs=[['current_situation','Current situation / process'],['current_solution','Current solution'],['pain_points','Main pain points'],['expected_benefits','Expected benefits'],['stakeholders','Key stakeholders'],['implementation_timeline','Target timeline'],['budget_assumptions','Budget / cost assumptions'],['roi_assumptions','ROI assumptions'],['risks','Known risks or concerns']];return `<div class="form-grid">${defs.map(([k,l])=>`<div class="field"><label>${esc(l)}</label><textarea data-assumption="${k}" placeholder="Optional">${esc(v[k]||'')}</textarea></div>`).join('')}</div>`}
function previewHtml(out){const order=['executive_summary','current_situation','objectives','why_this_product','requirement_fit','expected_benefits','financial_roi_assumptions','implementation_approach','risks_mitigations','alternatives_considered','recommendation','next_steps'];return `<div class="preview"><span class="badge">Temporary preview · not yet saved</span>${order.map(k=>out?.[k]?.content?`<section><h3>${esc(out[k].title||k.replaceAll('_',' '))}</h3><p>${esc(out[k].content)}</p></section>`:'').join('')}</div>`}
async function init(){try{const [auth,data]=await Promise.all([json('/api/auth/csrf'),json('/api/software/'+encodeURIComponent(product))]);const p=data.product;if(!p?.id)throw new Error('Product unavailable');const saved=draft();if(auth.user){app.innerHTML=`<p class="muted">Selected product: <b>${esc(p.name)}</b></p>${fields(saved)}<div class="actions"><button id="create" class="btn primary">Create Business Case</button><a class="btn" href="/software/${encodeURIComponent(product)}">Back to product</a></div><p id="status" class="status"></p>`;document.getElementById('create').onclick=async e=>{const b=e.currentTarget,assumptions=values();saveDraft(assumptions);b.disabled=true;document.getElementById('status').textContent='Preparing your saved business case…';try{const created=await json('/api/business-cases',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':auth.csrf_token||''},body:JSON.stringify({product_id:Number(p.id),consultation_id:consultation||0,assumptions})});sessionStorage.removeItem(DRAFT);location.href='/business-case?id='+encodeURIComponent(created.id)}catch(err){b.disabled=false;const s=document.getElementById('status');s.className='status err';s.textContent=err.message}};return}
 const a=activeConsultation(),token=a?.c?.public_token||'';if(!/^[a-f0-9]{48}$/.test(token)){const q=encodeURIComponent(next);app.innerHTML=`<p class="muted">A recommendation consultation is required for an anonymous preview. You can still create a free account or sign in to build and save a business case for <b>${esc(p.name)}</b>.</p><div class="actions"><a class="btn primary" href="/register?next=${q}">Create account</a><a class="btn" href="/login?next=${q}">Log in</a><a class="btn" href="/software/${encodeURIComponent(product)}">Back to product</a></div>`;return}
 app.innerHTML=`<p class="muted">Selected product: <b>${esc(p.name)}</b></p><p class="muted">Add only what matters. All fields are optional; your existing consultation context is reused automatically.</p>${fields(saved)}<div class="actions"><button id="preview" class="btn primary">Generate free preview</button><a class="btn" href="/software/${encodeURIComponent(product)}">Back to product</a></div><p id="status" class="status"></p><div id="previewOut"></div>`;
 document.getElementById('preview').onclick=async e=>{const b=e.currentTarget,assumptions=values();saveDraft(assumptions);b.disabled=true;const s=document.getElementById('status');s.className='status';s.textContent='Generating your temporary business case preview…';try{const d=await json('/api/business-cases/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:Number(p.id),consultation_token:token,assumptions})});s.textContent='Preview generated. Create an account or sign in to save, edit and reopen it.';document.getElementById('previewOut').innerHTML=previewHtml(d.output);const q=encodeURIComponent(next);document.getElementById('previewOut').insertAdjacentHTML('afterend',`<div class="actions"><a class="btn primary" href="/register?next=${q}">Save & continue</a><a class="btn" href="/login?next=${q}">Log in to save</a></div>`)}catch(err){s.className='status err';s.textContent=err.message}finally{b.disabled=false}}
 }catch(err){app.innerHTML='<p class="status err">'+esc(err.message)+'</p><div class="actions"><a class="btn" href="/">Return to TechSelectAI</a></div>'}}
init();
</script></body></html>