const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let csrf='';
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json','X-CSRF-Token':csrf};const r=await fetch(url,opt);const d=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(d.error||'Request failed');if(d.csrf_token)csrf=d.csrf_token;return d;}
const listify=a=>(Array.isArray(a)&&a.length)?'<ul>'+a.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':'<span class="muted">None</span>';
function threshold(i){const ok=!+i.insufficient_data&&+i.sources_analyzed>=3&&+i.source_type_count>=2&&+i.confidence_score>=.65;return ok?'<div class="ok">Publication threshold met</div>':'<div class="warn">Needs more evidence/diversity/confidence before publication</div>';}
async function load(){try{const d=await api('/api/community-intelligence');const el=document.getElementById('list');el.innerHTML=d.items.map(i=>`<article class="card"><h2>${esc(i.product)}</h2><div><span class="pill">${esc(i.review_status)}</span></div><p><strong>${i.score_5==null?'—':esc(i.score_5)+'/5'}</strong> · ${esc(i.confidence_label||'')} confidence</p><p class="muted">${esc(i.sources_analyzed)} usable sources · ${esc(i.source_type_count)} source types · ${esc(i.last_analyzed_at||'')}</p>${threshold(i)}${+i.pending_policy_count?`<div class="warn">${esc(i.pending_policy_count)} source(s) awaiting policy review</div>`:''}${+i.excluded_signal_count?`<div class="warn">${esc(i.excluded_signal_count)} excluded signal(s)</div>`:''}<div class="themes"><div><h3>Strengths</h3>${listify(i.strengths)}</div><div><h3>Concerns</h3>${listify(i.concerns)}</div></div><p><button onclick="detail(${i.product_id})">Review sources & themes</button></p><div id="detail-${i.product_id}"></div></article>`).join('')||'<div class="card">No Community Intelligence records yet.</div>'; }catch(e){document.getElementById('msg').textContent=e.message}}
async function detail(id){try{const d=await api('/api/community-intelligence/'+id);const i=d.item;const src=d.sources.map(s=>`<div class="source"><a href="${esc(s.source_url)}" target="_blank" rel="noopener">${esc(s.source_name||s.source_type)}</a> · ${esc(s.access_policy)}<br><span class="muted">quality ${esc(s.source_quality??'—')} · independence ${esc(s.independence_score??'—')} · specificity ${esc(s.specificity_score??'—')} ${s.exclusion_reason?'· excluded: '+esc(s.exclusion_reason):''}</span></div>`).join('');document.getElementById('detail-'+id).innerHTML=`<h3>Theme detail</h3><div class="themes"><div><strong>Implementation</strong>${listify(i.themes?.implementation)}</div><div><strong>Support</strong>${listify(i.themes?.support)}</div><div><strong>Pricing / value</strong>${listify(i.themes?.pricing_value)}</div><div><strong>Integrations</strong>${listify(i.themes?.integrations)}</div><div><strong>Reliability</strong>${listify(i.themes?.reliability)}</div><div><strong>Usability</strong>${listify(i.themes?.usability)}</div><div><strong>Best fit</strong>${listify(i.themes?.best_fit)}</div><div><strong>Poor fit</strong>${listify(i.themes?.poor_fit)}</div></div><h3>Sources</h3>${src||'<span class="muted">No sources</span>'}<textarea id="notes-${id}" placeholder="Review notes / evidence request"></textarea><div class="actions"><button onclick="reviewCI(${id},'approve')">Approve Intelligence</button><button class="secondary" onclick="reviewCI(${id},'request_more_evidence')">Request more evidence</button><button class="danger" onclick="reviewCI(${id},'reject')">Reject</button></div>`;}catch(e){document.getElementById('msg').textContent=e.message}}
async function reviewCI(id,action){const notes=document.getElementById('notes-'+id)?.value||'';try{await api(`/api/community-intelligence/${id}/review`,{method:'POST',body:JSON.stringify({action,notes})});document.getElementById('msg').textContent='Community Intelligence review saved and audited.';await load();}catch(e){document.getElementById('msg').textContent=e.message}}
load();
