<?php
require_once __DIR__.'/app/lib/Db.php';
$config=require __DIR__.'/app/config.php';
$pdo=Db::pdo();

function dg_h($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function dg_status($v){$v=(string)$v;return match($v){'supported'=>'Supported','partially_supported','partial','conditional'=>'Conditional / partial','not_supported'=>'Not supported',default=>'Not yet verified'};}
function dg_status_class($v){$v=(string)$v;return match($v){'supported'=>'ok','partially_supported','partial','conditional'=>'partial','not_supported'=>'no',default=>'unknown'};}

$guides=[
 'crm-saudi-arabia'=>[
  'title'=>'CRM Software for Saudi Companies: Evidence-Based Selection Guide',
  'description'=>'Compare CRM options for Saudi organizations using TechSelectAI’s verified capability, deployment and evidence data—without inventing a universal winner.',
  'eyebrow'=>'Saudi Arabia · CRM decision guide',
  'type'=>'category','category'=>'crm',
  'intro'=>'Saudi companies choosing a CRM usually need to balance sales-process fit, integrations, deployment, governance, implementation effort and commercial terms. This guide uses the same recorded TechSelectAI product facts used by the advisory platform. It does not declare a generic “best CRM” when buyer-specific or Saudi-specific evidence is missing.',
  'factors'=>['Lead, account and opportunity management','Workflow automation and forecasting','Reporting and dashboards','API and Microsoft ecosystem integration','SSO and enterprise access controls','Deployment model and hosting preference','Saudi-specific commercial, support and data-residency requirements that still require buyer/vendor verification'],
  'notice'=>'TechSelectAI does not currently model a complete Saudi-specific score for every CRM product. Regional availability, local implementation capability, Arabic requirements, data residency and local commercial terms should be confirmed during the consultation and with the vendor or implementation partner.'
 ],
 'salesforce-vs-dynamics-enterprise'=>[
  'title'=>'Salesforce Sales Cloud vs Dynamics 365 Sales for Enterprise',
  'description'=>'Evidence-aware enterprise comparison of Salesforce Sales Cloud and Dynamics 365 Sales using recorded TechSelectAI capability facts.',
  'eyebrow'=>'Enterprise CRM comparison guide',
  'type'=>'compare','products'=>['salesforce-sales-cloud','dynamics-365-sales'],
  'intro'=>'Both products are established enterprise CRM options. The right choice depends on requirements, existing architecture and implementation constraints—not a generic winner label. The table below uses only currently recorded TechSelectAI facts and keeps unknown evidence separate from unsupported capability.',
  'factors'=>['Existing Microsoft 365 / Azure architecture','Lead and opportunity process complexity','Sales automation and forecasting depth','Integration and API requirements','Identity and SSO architecture','Implementation ecosystem and change-management capacity','Commercial assumptions that must be validated directly with vendors'],
  'notice'=>'This guide is not a buyer-specific Fit Score. Use a TechSelectAI consultation to apply mandatory requirements, deployment, integration, commercial and regional criteria to your organization.'
 ],
 'cloud-vs-self-hosted-crm'=>[
  'title'=>'Cloud vs Self-Hosted CRM: What Should Your Company Choose?',
  'description'=>'Compare public SaaS, self-hosted and on-premise CRM options using recorded TechSelectAI deployment evidence.',
  'eyebrow'=>'CRM deployment decision guide',
  'type'=>'deployment','category'=>'crm',
  'intro'=>'Deployment model can be a mandatory requirement rather than a preference. This guide shows what TechSelectAI has actually verified for the current CRM catalog and keeps unverified deployment claims visible instead of assuming support.',
  'factors'=>['Internal infrastructure and operations capacity','Data-residency or contractual hosting requirements','Upgrade and patching ownership','Customization and integration requirements','Availability and disaster-recovery responsibility','Security operating model','Total implementation and lifecycle cost—not just subscription price'],
  'notice'=>'A recorded deployment status describes currently verified product evidence. It does not prove that a specific edition, country, contract or architecture will satisfy your organization’s exact hosting or regulatory requirements.'
 ]
];

$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
$slug='';if(preg_match('#^/guides/([a-z0-9-]+)/?$#',$path,$m))$slug=$m[1];
if(!isset($guides[$slug])){http_response_code(404);echo '<!doctype html><html><body><h1>Guide not found</h1><p><a href="/">Return to TechSelectAI</a></p></body></html>';exit;}
$g=$guides[$slug];
$rows=[];$lastReviewed=null;$comparisonUrl=null;

if($g['type']==='category'){
 $st=$pdo->prepare("SELECT p.id,p.name,p.slug,p.short_description,p.last_reviewed_at,v.name vendor_name,
  (SELECT COUNT(*) FROM product_capabilities pc JOIN capabilities c ON c.id=pc.capability_id JOIN modules m ON m.id=c.module_id WHERE pc.product_id=p.id AND pc.edition_id IS NULL AND m.category_id=p.category_id) total_facts,
  (SELECT COUNT(*) FROM product_capabilities pc JOIN capabilities c ON c.id=pc.capability_id JOIN modules m ON m.id=c.module_id WHERE pc.product_id=p.id AND pc.edition_id IS NULL AND m.category_id=p.category_id AND pc.support_status<>'not_yet_verified') known_facts,
  (SELECT COUNT(*) FROM product_capabilities pc JOIN capabilities c ON c.id=pc.capability_id JOIN modules m ON m.id=c.module_id WHERE pc.product_id=p.id AND pc.edition_id IS NULL AND m.category_id=p.category_id AND pc.support_status='supported') supported_facts,
  (SELECT ROUND(AVG(pc.confidence_score)*100) FROM product_capabilities pc JOIN capabilities c ON c.id=pc.capability_id JOIN modules m ON m.id=c.module_id WHERE pc.product_id=p.id AND pc.edition_id IS NULL AND m.category_id=p.category_id AND pc.support_status<>'not_yet_verified') known_confidence
 FROM products p JOIN categories cat ON cat.id=p.category_id JOIN vendors v ON v.id=p.vendor_id WHERE p.status='active' AND cat.slug=? ORDER BY p.name");
 $st->execute([$g['category']]);$rows=$st->fetchAll();
}elseif($g['type']==='compare'){
 $a=$g['products'][0];$b=$g['products'][1];
 $p=$pdo->prepare("SELECT p.id,p.name,p.slug,p.short_description,p.last_reviewed_at,v.name vendor_name FROM products p JOIN vendors v ON v.id=p.vendor_id WHERE p.slug IN(?,?) AND p.status='active'");$p->execute([$a,$b]);$products=[];foreach($p->fetchAll() as $r)$products[$r['slug']]=$r;
 if(count($products)===2){$pair=[$a,$b];sort($pair,SORT_STRING);$comparisonUrl='/compare/'.implode('-vs-',$pair);}
 $st=$pdo->prepare("SELECT c.name capability_name,c.slug capability_slug,pa.support_status a_status,pa.confidence_score a_confidence,pa.limitations a_limitations,pb.support_status b_status,pb.confidence_score b_confidence,pb.limitations b_limitations
 FROM products a JOIN products b ON b.slug=? JOIN product_capabilities pa ON pa.product_id=a.id AND pa.edition_id IS NULL JOIN product_capabilities pb ON pb.product_id=b.id AND pb.capability_id=pa.capability_id AND pb.edition_id IS NULL JOIN capabilities c ON c.id=pa.capability_id WHERE a.slug=? ORDER BY c.name");
 $st->execute([$b,$a]);$rows=$st->fetchAll();$g['product_records']=$products;
}elseif($g['type']==='deployment'){
 $st=$pdo->prepare("SELECT p.name,p.slug,p.last_reviewed_at,v.name vendor_name,d.name deployment_name,d.slug deployment_slug,pd.support_status,pd.confidence_score
 FROM products p JOIN categories c ON c.id=p.category_id JOIN vendors v ON v.id=p.vendor_id CROSS JOIN deployment_models d LEFT JOIN product_deployments pd ON pd.product_id=p.id AND pd.deployment_model_id=d.id WHERE p.status='active' AND c.slug=? AND d.slug IN('public-saas','private-cloud','self-hosted','on-premise','hybrid') ORDER BY p.name,d.name");
 $st->execute([$g['category']]);$raw=$st->fetchAll();$by=[];foreach($raw as $r){$k=$r['slug'];if(!isset($by[$k]))$by[$k]=['name'=>$r['name'],'slug'=>$r['slug'],'vendor_name'=>$r['vendor_name'],'last_reviewed_at'=>$r['last_reviewed_at'],'deployments'=>[]];$by[$k]['deployments'][$r['deployment_slug']]=['name'=>$r['deployment_name'],'status'=>$r['support_status']?:'not_yet_verified','confidence'=>$r['confidence_score']];}$rows=array_values($by);
}

foreach($rows as $r){$d=$r['last_reviewed_at']??null;if($d&&(!$lastReviewed||strtotime($d)>strtotime($lastReviewed)))$lastReviewed=$d;}
if($g['type']==='compare'&&!empty($g['product_records']))foreach($g['product_records'] as $r){$d=$r['last_reviewed_at']??null;if($d&&(!$lastReviewed||strtotime($d)>strtotime($lastReviewed)))$lastReviewed=$d;}
$canonical=rtrim($config['site_url'],'/').'/guides/'.$slug;
$schema=['@context'=>'https://schema.org','@type'=>'Article','headline'=>$g['title'],'description'=>$g['description'],'mainEntityOfPage'=>$canonical,'publisher'=>['@type'=>'Organization','name'=>'TechSelectAI','url'=>rtrim($config['site_url'],'/')]];
if($lastReviewed)$schema['dateModified']=date('Y-m-d',strtotime($lastReviewed));
$breadcrumb=['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[
 ['@type'=>'ListItem','position'=>1,'name'=>'TechSelectAI','item'=>rtrim($config['site_url'],'/').'/' ],
 ['@type'=>'ListItem','position'=>2,'name'=>'Decision Guides','item'=>rtrim($config['site_url'],'/').'/guides/'.$slug],
 ['@type'=>'ListItem','position'=>3,'name'=>$g['title'],'item'=>$canonical]
]];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=dg_h($g['title'])?> | TechSelectAI</title><meta name="description" content="<?=dg_h($g['description'])?>"><link rel="canonical" href="<?=dg_h($canonical)?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:title" content="<?=dg_h($g['title'])?>"><meta property="og:description" content="<?=dg_h($g['description'])?>"><meta property="og:url" content="<?=dg_h($canonical)?>"><meta property="og:type" content="article"><script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><script type="application/ld+json"><?=json_encode($breadcrumb,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f6f8fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1160px;margin:auto;padding:0 22px}.nav{display:flex;align-items:center;justify-content:space-between;padding:20px 0}.nav img{height:38px;max-width:230px}.nav a{color:#173b63;text-decoration:none}.hero{padding:56px 0 34px}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#237a7b}.hero h1{font-size:clamp(34px,5vw,58px);line-height:1.04;max-width:960px;margin:12px 0 18px}.lead{font-size:19px;line-height:1.65;max-width:880px;color:#475569}.meta{color:#64748b;font-size:13px}.grid{display:grid;grid-template-columns:1.45fr .75fr;gap:24px;align-items:start}.card{background:white;border:1px solid #dfe5ec;border-radius:16px;padding:22px;margin-bottom:18px;box-shadow:0 5px 24px rgba(15,23,42,.04)}h2{font-size:26px;margin-top:0}h3{margin:0 0 8px}.factors{padding-left:20px;line-height:1.75}.notice{border-left:4px solid #319795;background:#eefafa;padding:16px 18px;border-radius:10px;margin:20px 0}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #e5e7eb;padding:12px 10px}th{background:#f8fafc}.badge{display:inline-block;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:700}.ok{background:#e8f7ef;color:#17603a}.partial{background:#fff7db;color:#7a5900}.unknown{background:#eef2f6;color:#536171}.no{background:#fdecec;color:#8a2525}.cta{background:#173b63;color:white;border-radius:18px;padding:26px}.cta a{display:inline-block;margin-top:10px;background:white;color:#173b63;font-weight:800;padding:11px 16px;border-radius:10px;text-decoration:none}.links a{display:block;padding:7px 0}.small{font-size:13px;color:#64748b}.footer{padding:35px 0 50px;color:#64748b;font-size:13px}@media(max-width:820px){.grid{grid-template-columns:1fr}.hero{padding-top:28px}.nav{align-items:flex-start;gap:14px}.nav img{height:32px}}
</style></head><body><div class="wrap"><nav class="nav"><a href="/" aria-label="TechSelectAI home"><img src="/techselectai-logo.svg" alt="TechSelectAI"></a><div><a href="/methodology">Methodology</a> · <a href="/trust">Trust</a> · <a href="/software">Software</a></div></nav><main><section class="hero" id="overview" data-citation-section><div class="eyebrow"><?=dg_h($g['eyebrow'])?></div><h1><?=dg_h($g['title'])?></h1><p class="lead"><?=dg_h($g['intro'])?></p><p class="meta">Evidence-aware decision content · <?= $lastReviewed?'Catalog last reviewed '.dg_h(date('F Y',strtotime($lastReviewed))):'Review date varies by product' ?></p></section><div class="grid"><div><section class="card"><h2>What should drive the decision?</h2><ul class="factors"><?php foreach($g['factors'] as $f):?><li><?=dg_h($f)?></li><?php endforeach;?></ul><div class="notice"><strong>Evidence boundary:</strong> <?=dg_h($g['notice'])?></div></section>
<?php if($g['type']==='category'):?>
<section class="card" id="catalog-options" data-citation-section><h2>Current CRM catalog evidence</h2><p class="small">Products are shown alphabetically. Evidence coverage is not a product ranking and does not mean a product with fewer known facts is worse.</p><div class="table-wrap"><table><thead><tr><th>Product</th><th>Known evidence</th><th>Supported facts</th><th>Avg. known confidence</th></tr></thead><tbody><?php foreach($rows as $r):$total=max(1,(int)$r['total_facts']);?><tr><td><a href="/software/<?=dg_h($r['slug'])?>"><strong><?=dg_h($r['name'])?></strong></a><br><span class="small"><?=dg_h($r['vendor_name'])?></span></td><td><?= (int)$r['known_facts'] ?>/<?= (int)$r['total_facts'] ?> criteria</td><td><?= (int)$r['supported_facts'] ?></td><td><?= $r['known_confidence']!==null?(int)$r['known_confidence'].'%':'Not enough evidence' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php elseif($g['type']==='compare'): $products=$g['product_records']??[];$a=$g['products'][0];$b=$g['products'][1];?>
<section class="card" id="capability-comparison" data-citation-section><h2>Recorded capability evidence</h2><?php if(count($products)!==2):?><p>Comparison products are not available in the current catalog.</p><?php else:?><p><strong><?=dg_h($products[$a]['name'])?></strong> and <strong><?=dg_h($products[$b]['name'])?></strong> are compared only on shared recorded capability rows.</p><div class="table-wrap"><table><thead><tr><th>Capability</th><th><?=dg_h($products[$a]['name'])?></th><th><?=dg_h($products[$b]['name'])?></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=dg_h($r['capability_name'])?></td><td><span class="badge <?=dg_status_class($r['a_status'])?>"><?=dg_h(dg_status($r['a_status']))?></span><br><span class="small">Confidence <?=round((float)$r['a_confidence']*100)?>%<?=!empty($r['a_limitations'])?' · '.dg_h($r['a_limitations']):''?></span></td><td><span class="badge <?=dg_status_class($r['b_status'])?>"><?=dg_h(dg_status($r['b_status']))?></span><br><span class="small">Confidence <?=round((float)$r['b_confidence']*100)?>%<?=!empty($r['b_limitations'])?' · '.dg_h($r['b_limitations']):''?></span></td></tr><?php endforeach;?></tbody></table></div><?php if($comparisonUrl):?><p><a href="<?=dg_h($comparisonUrl)?>">Open the full product comparison →</a></p><?php endif;?><?php endif;?></section>
<?php elseif($g['type']==='deployment'):?>
<section class="card" id="deployment-options" data-citation-section><h2>Verified CRM deployment options</h2><p class="small">Unknown means TechSelectAI has not yet verified the deployment claim; it does not mean unsupported.</p><div class="table-wrap"><table><thead><tr><th>Product</th><th>Public SaaS</th><th>Self-hosted</th><th>On-premise</th><th>Private cloud</th><th>Hybrid</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><a href="/software/<?=dg_h($r['slug'])?>"><strong><?=dg_h($r['name'])?></strong></a></td><?php foreach(['public-saas','self-hosted','on-premise','private-cloud','hybrid'] as $ds):$d=$r['deployments'][$ds]??['status'=>'not_yet_verified','confidence'=>null];?><td><span class="badge <?=dg_status_class($d['status'])?>"><?=dg_h(dg_status($d['status']))?></span><?php if($d['confidence']!==null):?><br><span class="small"><?=round((float)$d['confidence']*100)?>% confidence</span><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<section class="card" id="how-to-use" data-citation-section><h2>How to use this guide</h2><p>Use this page to identify the questions worth validating. A real recommendation should then apply your mandatory capabilities, integrations, deployment, security/compliance, commercial, regional and implementation requirements through TechSelectAI’s deterministic scoring methodology.</p><p><a href="/methodology">See how TechSelectAI scoring works →</a></p></section></div><aside><section class="cta"><h2>Get a buyer-specific answer</h2><p>Tell TechSelectAI what your company actually needs. Your recommendation will separate Fit Score from Evidence Confidence and keep unknown evidence visible.</p><a href="/">Start a personalized consultation</a></section><section class="card links"><h3>Related decision guides</h3><?php foreach($guides as $k=>$item):if($k===$slug)continue;?><a href="/guides/<?=dg_h($k)?>"><?=dg_h($item['title'])?></a><?php endforeach;?><hr><a href="/categories/crm">Browse CRM evidence</a><a href="/trust">Trust & ownership disclosure</a></section></aside></div></main><footer class="footer">TechSelectAI decision guides are generated from the same canonical catalog used by the advisory platform. Commercial relationships do not determine recommendation scores or rankings.</footer></div></body></html>