<?php
require_once __DIR__.'/app/lib/Db.php';
require_once __DIR__.'/app/lib/Security.php';
require_once __DIR__.'/app/lib/UserConsultationHistory.php';
Security::start();
$user=Security::user();
if(!$user){header('Location: /login?next='.rawurlencode('/my-consultations'));exit;}
$rows=UserConsultationHistory::listForUser(Db::pdo(),(int)$user['id'],50);
function mc_e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Consultations | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#f7f9fc;color:#172033}.wrap{max-width:1100px;margin:34px auto;padding:0 20px}.head{display:flex;justify-content:space-between;gap:16px;align-items:center}.head a{color:#123b67}.card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:18px;margin:14px 0}.meta{color:#64748b;font-size:13px}.problem{line-height:1.55}.top{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.pill{padding:5px 8px;border-radius:999px;background:#eef4f8;font-size:12px}.empty{background:#fff;border:1px dashed #cbd5e1;border-radius:14px;padding:24px}.actions a{display:inline-block;margin-right:8px;margin-top:10px;text-decoration:none;font-weight:700}.new{padding:10px 14px;border-radius:10px;background:#123b67;color:#fff!important}@media(max-width:650px){.head{display:block}.head .new{margin-top:12px}}</style></head><body><main class="wrap"><div class="head"><div><h1>My Consultations</h1><p class="meta">Saved software and technology searches linked to your TechSelectAI account.</p></div><a class="new" href="/">Start new consultation</a></div><?php if(!$rows):?><div class="empty"><h2>No saved consultations yet</h2><p>Start a consultation while signed in, or sign in after an anonymous consultation to attach it to your account.</p><a class="new" href="/">Start software search</a></div><?php else:?><?php foreach($rows as $c):?><article class="card"><div class="meta"><?=mc_e($c['category']?:'Category not confirmed')?> · <?=mc_e(ucwords(str_replace('_',' ',$c['status'])))?> · Updated <?=mc_e(date('M j, Y H:i',strtotime((string)$c['updated_at'])))?></div><h2><?=mc_e($c['title']?:'Software consultation')?></h2><p class="problem"><?=mc_e($c['business_problem'])?></p><?php if(!empty($c['top_recommendations'])):?><div class="top"><?php foreach($c['top_recommendations'] as $r):?><span class="pill">#<?=intval($r['recommendation_rank'])?> <?=mc_e($r['name'])?> · <?=number_format((float)$r['overall_score'],0)?>%</span><?php endforeach;?></div><?php endif;?><div class="actions"><a href="/resume-consultation/<?=rawurlencode($c['public_token'])?>">Reopen consultation</a><?php if((int)$c['recommendation_count']>0):?><span class="meta">Recommendations saved</span><?php endif;?></div></article><?php endforeach;?><?php endif;?></main></body></html>
