<?php
require_once __DIR__.'/app/lib/Security.php';
Security::start();
if(!Security::user()){header('Location: /login');exit;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Reviews | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;background:#f7f9fc;color:#14213d;margin:0}main{max-width:980px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px;margin-top:14px}.meta{color:#64748b;font-size:13px}.row{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.badges{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:12px;font-weight:700}.badge.ok{background:#ecfdf5;color:#047857}.badge.warn{background:#fff7ed;color:#c2410c}.badge.bad{background:#fef2f2;color:#b91c1c}.reward{margin-top:14px;padding:12px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0}.muted{color:#64748b}.empty{padding:20px;background:#fff;border:1px dashed #cbd5e1;border-radius:16px;margin-top:18px}a{color:#075985;text-decoration:none;font-weight:700}.score{font-size:24px;font-weight:850;color:#0f172a}@media(max-width:620px){.row{display:block}.score{margin-top:10px}}</style></head><body><main><div class="top"><div><h1>My Verified Reviews</h1><p class="muted">Track moderation, verification and reward status for reviews you submitted to TechSelectAI.</p></div><a href="/">Back to TechSelectAI</a></div><div id="msg" class="muted">Loading...</div><div id="list"></div></main><script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function moderation(s){return ({pending:['Pending moderation','warn'],needs_more_verification:['Needs more verification','warn'],approved:['Approved','ok'],rejected:['Rejected','bad']})[s]||[String(s||'Unknown'),'']);}
function rewardLabel(type){return type==='cardiq_pro_voucher'?'CardIQ Pro voucher':type==='premium_report_access'?'Premium TechSelectAI report / benchmark access':'';}
function rewardStatus(r){if(!r.reward_type)return 'No reward assigned yet';if(r.reward_status==='issued')return 'Issued';if(r.reward_status==='redeemed')return 'Redeemed';if(r.reward_status==='expired')return 'Expired';if(r.reward_status==='cancelled')return 'Cancelled';if(r.reward_eligibility_status==='eligible')return 'Eligible';return 'Pending eligibility review';}
(async()=>{const msg=document.getElementById('msg'),box=document.getElementById('list');try{let res=await fetch('/api/reviews/mine');if(res.status===401){location.href='/login';return}let d=await res.json();if(!res.ok)throw new Error(d.error||'Unable to load reviews');msg.textContent='';if(!d.reviews.length){box.innerHTML='<div class="empty">You have not submitted a review yet. Open any software page and choose <strong>Write a verified review</strong>.</div>';return}box.innerHTML=d.reviews.map(r=>{let m=moderation(r.moderation_status),reward=rewardLabel(r.reward_type);return `<article class="card"><div class="row"><div><h2><a href="/software/${esc(r.product_slug)}">${esc(r.product)}</a></h2><div class="meta">Submitted ${esc(r.submitted_at)}${r.updated_at?' · Updated '+esc(r.updated_at):''}</div><div class="badges"><span class="badge ${m[1]}">${esc(m[0])}</span><span class="badge">${esc((r.verification_level||'email_verified').replaceAll('_',' '))}</span></div></div><div class="score">${esc(r.overall_rating)} / 5</div></div><div class="reward"><strong>Reward status</strong><div>${esc(reward?reward+' · '+rewardStatus(r):rewardStatus(r))}</div>${r.reward_expires_at?`<div class="meta">Expires ${esc(r.reward_expires_at)}</div>`:''}<div class="meta">Rewards are based on eligible verified participation, not whether a review is positive or negative.</div></div></article>`}).join('')}catch(e){msg.textContent=e.message}})();
</script></body></html>
