<?php
require_once __DIR__.'/app/lib/Entitlements.php';
$features=Entitlements::matrix();
$groups=['Public'=>[],'Registered'=>[]];
foreach($features as $feature=>$tier){
    $label=str_replace('_',' ',ucwords($feature,'_'));
    if($tier===Entitlements::PUBLIC)$groups['Public'][]=$label;
    else $groups['Registered'][]=$label;
}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TechSelectAI Access — Public and Free Registered</title><meta name="description" content="TechSelectAI keeps public software research open and provides the full current decision-support toolset to free registered users while the platform matures."><link rel="canonical" href="https://techselectai.com/plans"><style>body{font-family:Inter,Arial,sans-serif;background:#f7f9fc;color:#14213d;margin:0}main{max-width:1100px;margin:auto;padding:40px 22px}h1{font-size:38px;margin-bottom:8px}.lead{color:#475569;max-width:780px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:28px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:22px}.card h2{margin-top:0}.badge{font-size:12px;font-weight:700;background:#e0f2fe;padding:4px 8px;border-radius:999px}.note{margin-top:28px;padding:18px;background:#fff;border:1px solid #e2e8f0;border-radius:14px}li{margin:9px 0}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><main><p><a href="/">← TechSelectAI</a></p><h1>Access levels</h1><p class="lead">Public research stays open and crawlable. Creating a free account unlocks the complete current TechSelectAI software-selection workspace, including advanced decision-support tools. Paid plans are intentionally deferred while the product matures.</p><div class="grid"><?php foreach($groups as $name=>$items): ?><section class="card"><span class="badge"><?=h($name)?></span><h2><?=h($name==='Public'?'Public / no login':'Free registered')?></h2><ul><?php foreach($items as $item): ?><li><?=h($item)?></li><?php endforeach; ?></ul></section><?php endforeach; ?></div><div class="note"><strong>Boundary:</strong> TechSelectAI supports software discovery and decision-making through the final decision pack. Purchase requisitions, approvals, purchase orders, contract execution, invoicing and procurement operations remain outside scope.</div></main></body></html>
