<?php
require_once __DIR__.'/app/lib/Security.php';Security::start();Security::requireRole(['reviewer','admin','super_admin']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verified Review Moderation | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;background:#f7f9fc;color:#14213d;margin:0}main{max-width:1180px;margin:auto;padding:28px}.toolbar,.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.card{margin-top:16px}.meta{color:#64748b;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ratings{display:flex;gap:10px;flex-wrap:wrap}.badge{background:#eef2ff;border-radius:999px;padding:4px 8px;font-size:12px}button,select,input,textarea{padding:9px;border-radius:8px;border:1px solid #cbd5e1}button{background:#075985;color:white;border:0;cursor:pointer}.danger{background:#b91c1c}.secondary{background:#475569}textarea{width:100%;min-height:80px;box-sizing:border-box}.actions{display:flex;gap:8px;flex-wrap:wrap}.section{margin-top:14px}.err{color:#b91c1c}.ok{color:#166534}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><main><p><a href="/admin">← Admin</a></p><h1>Verified Review Moderation</h1><div class="toolbar"><label>Status <select id="filter"><option value="pending">Pending</option><option value="needs_more_verification">Needs more verification</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="">All</option></select></label><button onclick="load()">Refresh</button><span id="msg"></span></div><div id="reviews"></div></main><script>
async function csrf(){let d=await fetch('/api/auth/csrf').then(r=>r.json());if(d.csrf_token)localStorage.setItem('csrf',d.csrf_token)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json','X-CSRF-Token':localStorage.getItem('csrf')||''};let r=await fetch(url,opt),d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function e(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function rating(label,v){return v?`<span class="badge">${e(label)} ${e(v)}/5</span>`:''}
async function load(){let box=document.getElementById('reviews'),msg=document.getElementById('msg');try{msg.textContent='Loading...';let s=document.getElementById('filter').value;let d=await api('/api/review-admin/reviews'+(s?'?status='+encodeURIComponent(s):''));box.innerHTML=d.reviews.map(r=>`<article class="card"><div class="grid"><div><h2>${e(r.product)}</h2><div class="meta">Submitted ${e(r.submitted_at)} · ${e(r.reviewer_name||'Verified reviewer')} · ${e(r.reviewer_role||'Role not provided')} · ${e(r.reviewer_industry||'Industry not provided')}</div></div><div><strong>Status:</strong> ${e(r.moderation_status)}<br><strong>Verification:</strong> ${e(r.verification_level||'email_verified')}<br><strong>Open risk flags:</strong> ${e(r.open_risk_flags||0)}</div></div><div class="section ratings">${rating('Overall',r.overall_rating)}${rating('Ease',r.ease_of_use_rating)}${rating('Implementation',r.implementation_rating)}${rating('Support',r.support_rating)}${rating('Value',r.value_for_money_rating)}${rating('Reliability',r.reliability_rating)}</div><div class="grid section"><div><strong>Pros</strong><p>${e(r.pros||'—')}</p></div><div><strong>Cons</strong><p>${e(r.cons||'—')}</p></div></div><div class="section"><strong>Improvements</strong><p>${e(r.improvements||'—')}</p></div><div class="section"><label>Moderation notes</label><textarea id="notes-${r.id}">${e(r.moderation_notes||'')}</textarea><div class="actions"><button onclick="moderate(${r.id},'approved')">Approve</button><button class="secondary" onclick="moderate(${r.id},'needs_more_verification')">Need verification</button><button class="danger" onclick="moderate(${r.id},'rejected')">Reject</button></div></div><div class="grid section"><div><label>Add verification</label><select id="level-${r.id}"><option value="business_domain_verified">Business domain</option><option value="proof_of_use_verified">Proof of use</option><option value="admin_verified">Admin verified</option></select><button onclick="verifyReview(${r.id})">Mark verified</button></div><div><label>Risk flag</label><input id="flag-${r.id}" placeholder="e.g. duplicate_pattern"><select id="sev-${r.id}"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select><button class="secondary" onclick="flagReview(${r.id})">Add flag</button></div></div></article>`).join('')||'<p>No reviews in this queue.</p>';msg.textContent=`${d.reviews.length} review(s)`}catch(err){msg.className='err';msg.textContent=err.message}}
async function moderate(id,status){try{await api(`/api/review-admin/reviews/${id}/moderate`,{method:'PATCH',body:JSON.stringify({status,notes:document.getElementById('notes-'+id).value})});await load()}catch(err){alert(err.message)}}
async function verifyReview(id){try{await api(`/api/review-admin/reviews/${id}/verification`,{method:'PUT',body:JSON.stringify({level:document.getElementById('level-'+id).value,status:'verified'})});await load()}catch(err){alert(err.message)}}
async function flagReview(id){try{await api(`/api/review-admin/reviews/${id}/risk-flags`,{method:'POST',body:JSON.stringify({flag_type:document.getElementById('flag-'+id).value,severity:document.getElementById('sev-'+id).value})});await load()}catch(err){alert(err.message)}}
csrf().then(load);
</script></body></html>