<?php
require_once __DIR__.'/app/lib/Security.php';Security::start();Security::requireRole(['reviewer','admin','super_admin']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verified Review Rewards | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;background:#f7f9fc;color:#14213d;margin:0}main{max-width:1180px;margin:auto;padding:28px}.toolbar,.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px}.card{margin-top:14px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.muted{color:#64748b;font-size:13px}select,input,button{padding:9px;border-radius:8px;border:1px solid #cbd5e1;box-sizing:border-box;width:100%}button{background:#075985;color:#fff;border:0;cursor:pointer}.secondary{background:#475569}.danger{background:#b91c1c}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button{width:auto}.status{font-weight:800}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body><main><p><a href="/admin">← Admin</a></p><h1>Verified Review Rewards</h1><div class="toolbar"><p class="muted">Rewards recognize honest verified participation. Eligibility never depends on whether the review is positive or negative.</p><button style="width:auto" onclick="load()">Refresh</button><span id="msg"></span></div><div id="rows"></div></main><script>
async function csrf(){let d=await fetch('/api/auth/csrf').then(r=>r.json());if(d.csrf_token)localStorage.setItem('csrf',d.csrf_token)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json','X-CSRF-Token':localStorage.getItem('csrf')||''};let r=await fetch(url,opt),d=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function e(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function load(){let box=document.getElementById('rows'),msg=document.getElementById('msg');try{msg.textContent='Loading...';let d=await api('/api/review-rewards');box.innerHTML=d.rewards.map(r=>`<div class="card"><div class="grid"><div><strong>${e(r.product)}</strong><div class="muted">Review #${e(r.review_id)} · ${e(r.overall_rating)}/5</div></div><div><span class="status">${e(r.eligibility_status||'pending')}</span><div class="muted">Eligibility</div></div><div><span class="status">${e(r.issuance_status||'not_issued')}</span><div class="muted">Fulfillment</div></div><div><span class="status">${r.verified?'Verified':'Not verified'}</span><div class="muted">Review verification</div></div></div><div class="grid" style="margin-top:14px"><div><label>Reward</label><select id="t-${r.review_id}"><option value="cardiq_pro_voucher" ${r.reward_type==='cardiq_pro_voucher'?'selected':''}>CardIQ Pro voucher</option><option value="premium_report_access" ${r.reward_type==='premium_report_access'?'selected':''}>Premium TechSelectAI report / benchmark access</option></select></div><div><label>Reference (not stored raw)</label><input id="ref-${r.review_id}" placeholder="voucher/access reference"></div><div><label>Expiry</label><input id="exp-${r.review_id}" type="datetime-local"></div><div class="actions" style="align-items:end"><button onclick="eligible(${r.review_id})">Mark eligible</button><button onclick="issue(${r.review_id})">Issue</button><button class="secondary" onclick="mark(${r.review_id},'redeemed')">Redeemed</button><button class="danger" onclick="mark(${r.review_id},'cancelled')">Cancel</button></div></div></div>`).join('')||'<p>No approved verified reviews available for rewards.</p>';msg.textContent=d.rewards.length+' review(s)'}catch(err){msg.textContent=err.message}}
async function eligible(id){try{await api(`/api/review-rewards/${id}/eligible`,{method:'POST',body:JSON.stringify({reward_type:document.getElementById('t-'+id).value})});await load()}catch(e){alert(e.message)}}
async function issue(id){try{await api(`/api/review-rewards/${id}/issue`,{method:'POST',body:JSON.stringify({reference:document.getElementById('ref-'+id).value,expires_at:document.getElementById('exp-'+id).value||null})});await load()}catch(e){alert(e.message)}}
async function mark(id,status){try{await api(`/api/review-rewards/${id}/status`,{method:'POST',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
csrf().then(load);
</script></body></html>
