<?php
require_once __DIR__.'/app/lib/Security.php';Security::start();Security::requireRole(['admin','data_editor','reviewer','super_admin']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Taxonomy Expansion Queue | TechSelectAI</title><meta name="robots" content="noindex,nofollow"><style>body{font-family:Inter,Arial,sans-serif;background:#f7f9fc;color:#14213d;margin:0}main{max-width:1180px;margin:auto;padding:28px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}table{width:100%;border-collapse:collapse;margin-top:18px;background:#fff}th,td{padding:10px;border-bottom:1px solid #eef2f7;text-align:left;vertical-align:top}select,input{width:100%;box-sizing:border-box;padding:8px;border:1px solid #cbd5e1;border-radius:8px}button{padding:8px 12px;border:0;border-radius:8px;background:#075985;color:#fff;cursor:pointer}.muted{color:#64748b}.count{font-weight:800;font-size:20px}@media(max-width:760px){table{display:block;overflow:auto}}</style></head><body><main><p><a href="/admin">← Admin</a></p><div class="card"><h1>Taxonomy Expansion Queue</h1><p class="muted">Unmapped topics from general AI consultations are grouped here so catalog expansion is driven by real demand. Nothing here is added to the catalog automatically.</p><div id="msg"></div><table><thead><tr><th>Topic</th><th>Demand</th><th>Last seen</th><th>Example</th><th>Status</th><th>Priority</th><th>Notes</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></main><script>
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json','X-CSRF-Token':localStorage.getItem('csrf')||''};let r=await fetch(url,opt);let d=await r.json().catch(()=>({error:'Invalid response'}));if(r.status===401){location.href='/login';throw new Error('Sign in required')}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
(async()=>{let c=await fetch('/api/auth/csrf').then(r=>r.json());if(c.csrf_token)localStorage.setItem('csrf',c.csrf_token);await load()})();
async function load(){try{let d=await api('/api/taxonomy/queue');document.getElementById('rows').innerHTML=d.items.map(x=>`<tr><td><strong>${esc(x.topic_label)}</strong><br><small>${esc(x.topic_key)}</small></td><td class="count">${esc(x.occurrence_count)}</td><td>${esc(x.last_seen_at)}</td><td>${esc(x.latest_example_request||'')}</td><td><select id="s-${x.id}">${['new','researching','planned','added_to_catalog','ignored'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td><select id="p-${x.id}">${['high','normal','low'].map(v=>`<option ${x.priority===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input id="n-${x.id}" value="${esc(x.admin_notes||'')}"></td><td><button onclick="save(${x.id})">Save</button></td></tr>`).join('')}catch(e){document.getElementById('msg').textContent=e.message}}
async function save(id){let msg=document.getElementById('msg');try{await api('/api/taxonomy/queue/'+id,{method:'PATCH',body:JSON.stringify({status:document.getElementById('s-'+id).value,priority:document.getElementById('p-'+id).value,admin_notes:document.getElementById('n-'+id).value})});msg.textContent='Saved.';await load()}catch(e){msg.textContent=e.message}}
</script></body></html>
