<?php
require_once __DIR__.'/app/lib/Db.php';
$config=require __DIR__.'/app/config.php';
$pdo=Db::pdo();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function status_count(array $row,string $key):int{return isset($row[$key])?(int)$row[$key]:0;}

$slug='terminal-operating-systems';
$st=$pdo->prepare('SELECT id,name,description FROM categories WHERE slug=? AND is_active=1 LIMIT 1');
$st->execute([$slug]);$category=$st->fetch();
if(!$category){http_response_code(404);exit('Terminal Operating Systems research dataset is not available.');}

$q=$pdo->prepare("SELECT p.id,p.name,p.slug,p.short_description,p.last_reviewed_at,v.name vendor,
 COUNT(DISTINCT pc.id) capability_rows,
 COUNT(DISTINCT CASE WHEN pc.support_status='supported' THEN pc.id END) supported_count,
 COUNT(DISTINCT CASE WHEN pc.support_status IN('partially_supported','enterprise_only','plan_dependent','custom_configuration','addon','third_party_integration') THEN pc.id END) conditional_count,
 COUNT(DISTINCT CASE WHEN pc.support_status IN('unknown','not_yet_verified') THEN pc.id END) unknown_count,
 COUNT(DISTINCT CASE WHEN pc.support_status='not_supported' THEN pc.id END) unsupported_count,
 COUNT(DISTINCT es.id) evidence_count
 FROM products p
 LEFT JOIN vendors v ON v.id=p.vendor_id
 LEFT JOIN product_capabilities pc ON pc.product_id=p.id AND pc.edition_id IS NULL
 LEFT JOIN evidence_sources es ON es.product_id=p.id
 WHERE p.category_id=? AND p.status='active'
 GROUP BY p.id ORDER BY p.name");
$q->execute([$category['id']]);$products=$q->fetchAll();

$q=$pdo->prepare("SELECT m.name,m.slug,COUNT(c.id) capability_count FROM modules m JOIN capabilities c ON c.module_id=m.id AND c.is_active=1 WHERE m.category_id=? AND m.slug<>'mobile-access' GROUP BY m.id,m.name,m.slug ORDER BY m.id");
$q->execute([$category['id']]);$modules=$q->fetchAll();
$specialistCount=0;foreach($modules as $m)$specialistCount+=(int)$m['capability_count'];
$q=$pdo->prepare("SELECT COUNT(*) FROM capabilities c JOIN modules m ON m.id=c.module_id WHERE m.category_id=? AND m.slug='mobile-access' AND c.is_active=1");$q->execute([$category['id']]);$mobileCount=(int)$q->fetchColumn();
$q=$pdo->prepare("SELECT COUNT(DISTINCT es.id),MAX(es.checked_at) FROM evidence_sources es JOIN products p ON p.id=es.product_id WHERE p.category_id=? AND p.status='active'");$q->execute([$category['id']]);[$sourceCount,$latestEvidence]=$q->fetch(PDO::FETCH_NUM);
$q=$pdo->prepare("SELECT MAX(last_reviewed_at) FROM products WHERE category_id=? AND status='active'");$q->execute([$category['id']]);$lastReviewed=$q->fetchColumn();

$canonical=rtrim($config['site_url'],'/').'/research/terminal-operating-systems';
$itemList=[];foreach($products as $i=>$p)$itemList[]=['@type'=>'ListItem','position'=>$i+1,'name'=>$p['name'],'url'=>rtrim($config['site_url'],'/').'/software/'.$p['slug']];
$schema=['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'CollectionPage','@id'=>$canonical.'#page','url'=>$canonical,'name'=>'Terminal Operating Systems (TOS): Vendor Landscape, Capabilities & Selection Framework','description'=>'TechSelectAI specialist research hub for evidence-based Terminal Operating System selection for container and mixed-cargo terminals.','dateModified'=>$lastReviewed?date('Y-m-d',strtotime($lastReviewed)):date('Y-m-d'),'about'=>[['@type'=>'Thing','name'=>'Terminal Operating System'],['@type'=>'Thing','name'=>'Container terminal operations']],'mainEntity'=>['@type'=>'ItemList','name'=>'Terminal Operating Systems in the TechSelectAI research dataset','numberOfItems'=>count($itemList),'itemListElement'=>$itemList]],
 ['@type'=>'BreadcrumbList','itemListElement'=>[
  ['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>rtrim($config['site_url'],'/').'/'],
  ['@type'=>'ListItem','position'=>2,'name'=>'Research','item'=>rtrim($config['site_url'],'/').'/research/software-evidence-benchmark'],
  ['@type'=>'ListItem','position'=>3,'name'=>'Terminal Operating Systems','item'=>$canonical]
 ]]
]];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Terminal Operating Systems (TOS): Vendor Comparison & Selection Framework | TechSelectAI</title>
<meta name="description" content="Evidence-based Terminal Operating System research covering TOS vendors, 85 specialist capabilities, vessel, yard, gate, rail, automation, integrations, billing, special cargo and resilience.">
<link rel="canonical" href="<?=e($canonical)?>"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large">
<meta property="og:type" content="website"><meta property="og:site_name" content="TechSelectAI"><meta property="og:title" content="Terminal Operating Systems (TOS): Vendor Landscape & Selection Framework"><meta property="og:description" content="TechSelectAI specialist TOS research for evidence-based terminal software selection."><meta property="og:url" content="<?=e($canonical)?>">
<script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<style>:root{--navy:#153b66;--teal:#248d91;--ink:#182334;--muted:#667085;--line:#dfe7ee;--soft:#f5f9fb;--amber:#805600}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--ink);background:#fff;line-height:1.62}a{color:#1766a5}header{padding:17px max(22px,5vw);border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}header a.brand{font-weight:850;font-size:20px;color:var(--navy);text-decoration:none}nav a{margin-left:18px;text-decoration:none;font-weight:650}.wrap{max-width:1120px;margin:auto;padding:0 24px 60px}.hero{padding:48px 0 28px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:var(--teal);font-weight:800}.hero h1{font-size:clamp(37px,5.2vw,62px);line-height:1.04;margin:8px 0 16px;max-width:980px}.lead{font-size:20px;color:#506075;max-width:900px}.stats,.links{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.pill{background:#eef7f7;border:1px solid #d5e8e8;border-radius:999px;padding:8px 11px;font-size:13px;font-weight:750}.btn{display:inline-flex;padding:10px 14px;border-radius:10px;text-decoration:none;font-weight:750;border:1px solid #cdd9e2}.btn.primary{background:var(--navy);color:#fff;border-color:var(--navy)}.section{padding-top:38px}.section h2{font-size:29px;margin:0 0 9px}.intro{color:var(--muted);max-width:900px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:15px}.card{border:1px solid var(--line);border-radius:15px;padding:18px;background:#fff}.card h3{margin:0 0 7px;font-size:18px}.card p{color:var(--muted);margin:6px 0}.metric{font-size:12px;color:#536174;margin-top:10px}.notice{background:#fff9ec;border:1px solid #ecd9aa;border-radius:14px;padding:18px;color:#694b0e}.steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:13px}.step{background:var(--soft);border:1px solid var(--line);border-radius:14px;padding:17px}.step b{display:block;color:var(--navy);margin-bottom:5px}.footer-note{margin-top:42px;color:var(--muted);font-size:13px}@media(max-width:700px){nav{display:none}}</style></head><body>
<header><a class="brand" href="/">TechSelectAI</a><nav><a href="/categories/terminal-operating-systems">TOS category</a><a href="/research/tos-capability-taxonomy">TOS taxonomy</a><a href="/methodology">Methodology</a></nav></header>
<main class="wrap"><section class="hero"><div class="eyebrow">Specialist research · Ports, maritime & terminal operations</div><h1>Terminal Operating Systems (TOS): Vendor Landscape, Capabilities & Selection Framework</h1><p class="lead">TechSelectAI maintains a specialist, evidence-based research model for selecting Terminal Operating Systems used in container and mixed-cargo terminal operations. The model focuses on operational requirements—not review popularity—and separates verified product capability evidence from buyer-specific fit scoring.</p>
<div class="stats"><span class="pill"><?=count($products)?> active TOS products</span><span class="pill"><?=$specialistCount?> specialist TOS criteria</span><span class="pill"><?=$mobileCount?> mobile-access criteria tracked separately</span><span class="pill"><?=intval($sourceCount)?> recorded evidence sources</span></div>
<div class="links"><a class="btn primary" href="/categories/terminal-operating-systems">Compare TOS products</a><a class="btn" href="/research/tos-capability-taxonomy">Explore the capability taxonomy</a><a class="btn" href="/methodology">How evidence is evaluated</a></div></section>

<section class="section"><h2>What a modern TOS evaluation needs to cover</h2><p class="intro">A Terminal Operating System decision goes far beyond a generic software feature list. TechSelectAI's specialist model organizes the operational questions buyers commonly need to validate during discovery, shortlist, RFP and reference checks.</p><div class="grid"><?php foreach($modules as $m):?><article class="card"><div class="eyebrow">TOS module</div><h3><?=e($m['name'])?></h3><p><?=intval($m['capability_count'])?> buyer-selectable criteria in the current taxonomy.</p></article><?php endforeach;?></div></section>

<section class="section"><h2>Current TOS research dataset</h2><p class="intro">These are the active Terminal Operating Systems currently represented in the TechSelectAI dataset. Counts describe TechSelectAI's research coverage, not product quality or a universal ranking.</p><div class="grid"><?php foreach($products as $p):?><article class="card"><div class="eyebrow"><?=e($p['vendor']?:'Vendor')?></div><h3><a href="/software/<?=e($p['slug'])?>"><?=e($p['name'])?></a></h3><p><?=e($p['short_description']?:'Evidence-backed Terminal Operating System profile.')?></p><div class="metric"><?=status_count($p,'supported_count')?> supported · <?=status_count($p,'conditional_count')?> conditional · <?=status_count($p,'unknown_count')?> research pending · <?=status_count($p,'unsupported_count')?> explicitly unsupported · <?=status_count($p,'evidence_count')?> evidence sources</div></article><?php endforeach;?></div></section>

<section class="section"><h2>How to interpret TechSelectAI TOS evidence</h2><div class="notice"><strong>Not yet verified does not mean not supported.</strong> It means the current TechSelectAI evidence set has not established the exact capability. Vendor RFP responses, project-specific configuration, implementation documentation or terminal references may verify additional capability.</div><div class="steps" style="margin-top:15px"><div class="step"><b>Supported</b>Current evidence establishes the capability for the evaluated product or documented scope.</div><div class="step"><b>Conditional / partial</b>The capability may depend on an edition, add-on, companion module, third-party integration or implementation scope.</div><div class="step"><b>Not yet verified</b>Evidence is incomplete. TechSelectAI does not convert missing evidence into a negative product claim.</div><div class="step"><b>Not supported</b>Used only when evidence establishes that the evaluated product does not support the capability.</div></div></section>

<section class="section"><h2>Designed for TOS procurement and technical evaluation</h2><div class="steps"><div class="step"><b>1. Define terminal requirements</b>Capture vessel, yard, gate, rail, equipment, automation, cargo, integration, billing, resilience and security needs.</div><div class="step"><b>2. Review evidence</b>Separate demonstrated product capability from optional modules, implementation examples and claims that are still unverified.</div><div class="step"><b>3. Build the shortlist</b>Compare products against the buyer's actual must-have criteria rather than a generic market popularity list.</div><div class="step"><b>4. Validate through RFP</b>Use vendor responses, architecture workshops, reference terminals and implementation evidence to close remaining research gaps.</div></div></section>

<section class="section"><h2>Research transparency</h2><p class="intro">TechSelectAI is not claiming that every TOS capability is permanently verified or universally included in every implementation. Optional modules, companion products, integrations and project-specific configurations are kept explicit where the available evidence requires that distinction. Evidence confidence and product fit are separate signals.</p><div class="links"><a class="btn" href="/trust">Trust & independence</a><a class="btn" href="/about-techselectai">About / citation resource</a><a class="btn" href="/research/software-evidence-benchmark">Evidence benchmark</a></div><?php if($latestEvidence):?><p class="footer-note">Latest recorded TOS evidence check in the current dataset: <?=e(date('F j, Y',strtotime($latestEvidence)))?>.</p><?php endif;?></section></main></body></html>