<?php
require_once __DIR__.'/app/lib/Db.php';
$config=require __DIR__.'/app/config.php';
$pdo=Db::pdo();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$slug='terminal-operating-systems';
$st=$pdo->prepare('SELECT id,name FROM categories WHERE slug=? AND is_active=1 LIMIT 1');$st->execute([$slug]);$category=$st->fetch();
if(!$category){http_response_code(404);exit('Terminal Operating Systems taxonomy is not available.');}
$q=$pdo->prepare("SELECT m.name module_name,m.slug module_slug,c.name capability_name,c.slug capability_slug,c.description FROM modules m JOIN capabilities c ON c.module_id=m.id AND c.is_active=1 WHERE m.category_id=? ORDER BY m.id,c.id");
$q->execute([$category['id']]);$rows=$q->fetchAll();
$modules=[];$specialistCount=0;$mobileCount=0;
foreach($rows as $r){$modules[$r['module_name']][]=$r;if($r['module_slug']==='mobile-access')$mobileCount++;else $specialistCount++;}
$canonical=rtrim($config['site_url'],'/').'/research/tos-capability-taxonomy';
$terms=[];$pos=1;foreach($rows as $r){if($r['module_slug']==='mobile-access')continue;$terms[]=['@type'=>'DefinedTerm','position'=>$pos++,'name'=>$r['capability_name'],'termCode'=>$r['capability_slug'],'description'=>$r['description'],'inDefinedTermSet'=>$canonical];}
$schema=['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'TechArticle','@id'=>$canonical.'#article','url'=>$canonical,'headline'=>'Terminal Operating System Capability Taxonomy','description'=>'TechSelectAI specialist capability taxonomy for evaluating container-terminal and mixed-cargo Terminal Operating Systems.','about'=>['@type'=>'Thing','name'=>'Terminal Operating System']],
 ['@type'=>'DefinedTermSet','@id'=>$canonical,'name'=>'TechSelectAI Terminal Operating System Capability Taxonomy','description'=>'Buyer-selectable operational requirements used by TechSelectAI to structure TOS research and software selection.','hasDefinedTerm'=>$terms],
 ['@type'=>'BreadcrumbList','itemListElement'=>[
   ['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>rtrim($config['site_url'],'/').'/'],
   ['@type'=>'ListItem','position'=>2,'name'=>'TOS Research','item'=>rtrim($config['site_url'],'/').'/research/terminal-operating-systems'],
   ['@type'=>'ListItem','position'=>3,'name'=>'TOS Capability Taxonomy','item'=>$canonical]
 ]]
]];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Terminal Operating System Capability Taxonomy — 85 TOS Requirements | TechSelectAI</title>
<meta name="description" content="Explore TechSelectAI's 85-requirement Terminal Operating System capability taxonomy for vessel, yard, gate, rail, equipment, automation, cargo, integration, billing, resilience and security.">
<link rel="canonical" href="<?=e($canonical)?>"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large">
<meta property="og:type" content="article"><meta property="og:site_name" content="TechSelectAI"><meta property="og:title" content="Terminal Operating System Capability Taxonomy"><meta property="og:description" content="A structured TOS requirements framework for container-terminal software evaluation."><meta property="og:url" content="<?=e($canonical)?>">
<script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<style>:root{--navy:#153b66;--teal:#248d91;--ink:#182334;--muted:#667085;--line:#dfe7ee;--soft:#f6f9fb}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--ink);line-height:1.58}a{color:#1766a5}header{padding:17px max(22px,5vw);border-bottom:1px solid var(--line);display:flex;justify-content:space-between}header a{font-weight:750;text-decoration:none}.brand{font-size:20px;color:var(--navy)}.wrap{max-width:1120px;margin:auto;padding:0 24px 60px}.hero{padding:46px 0 26px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:var(--teal);font-weight:800}.hero h1{font-size:clamp(36px,5vw,58px);line-height:1.05;margin:8px 0 15px}.lead{font-size:19px;color:#526175;max-width:900px}.note{padding:17px;border:1px solid #d8e8ea;background:#f1f8f8;border-radius:13px;margin-top:18px}.module{padding-top:34px}.module h2{font-size:27px;margin:0 0 7px}.module-intro{color:var(--muted);margin:0 0 14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:12px}.cap{border:1px solid var(--line);border-radius:13px;padding:15px;background:#fff}.cap h3{font-size:16px;margin:0 0 6px}.cap p{font-size:13px;color:var(--muted);margin:0}.slug{font-size:11px;color:#718096;margin-top:8px;overflow-wrap:anywhere}.links{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.btn{padding:10px 13px;border:1px solid #ccd8e0;border-radius:9px;text-decoration:none;font-weight:750}.footer-note{margin-top:38px;color:var(--muted);font-size:13px}@media(max-width:650px){header span{display:none}}</style></head><body>
<header><a class="brand" href="/">TechSelectAI</a><span><a href="/research/terminal-operating-systems">TOS research hub</a> · <a href="/categories/terminal-operating-systems">Compare products</a></span></header>
<main class="wrap"><section class="hero"><div class="eyebrow">Original specialist framework · Terminal operations</div><h1>Terminal Operating System Capability Taxonomy</h1><p class="lead">TechSelectAI uses a domain-specific TOS requirements model to structure terminal software discovery, evidence research, comparison and buyer requirement capture. The current framework contains <strong><?=$specialistCount?> specialist operational criteria</strong> across nine TOS modules, with <?=$mobileCount?> mobile-access criteria tracked separately.</p><div class="note"><strong>Taxonomy depth is not evidence depth.</strong> A criterion appearing here means it is relevant to TOS evaluation; it does not mean every product supports it. Product support is established separately from evidence and may remain <em>not yet verified</em>.</div><div class="links"><a class="btn" href="/research/terminal-operating-systems">TOS vendor landscape</a><a class="btn" href="/categories/terminal-operating-systems">TOS category comparison</a><a class="btn" href="/methodology">Evaluation methodology</a></div></section>
<?php foreach($modules as $module=>$caps):?><section class="module"><div class="eyebrow"><?=e($module==='Mobile Access'?'Cross-category selection criteria':'TOS operational module')?></div><h2><?=e($module)?></h2><p class="module-intro"><?=count($caps)?> buyer-selectable criteria.</p><div class="grid"><?php foreach($caps as $cap):?><article class="cap"><h3><a href="/capabilities/<?=e($cap['capability_slug'])?>"><?=e($cap['capability_name'])?></a></h3><p><?=e($cap['description'])?></p><div class="slug"><?=e($cap['capability_slug'])?></div></article><?php endforeach;?></div></section><?php endforeach;?>
<p class="footer-note">Use this taxonomy as a requirements framework, not as a claim that every listed capability is standard in every TOS. Critical requirements should be validated through current vendor documentation, RFP responses, solution architecture, reference terminals and implementation evidence.</p></main></body></html>