-- V1 release security/auth/fit additions
SET NAMES utf8mb4;
START TRANSACTION;
CREATE TABLE IF NOT EXISTS auth_tokens(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,token_hash BINARY(32) NOT NULL UNIQUE,purpose VARCHAR(32) NOT NULL,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_auth_user(user_id,purpose),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,bucket_key VARBINARY(32) NOT NULL,route_key VARCHAR(120) NOT NULL,window_start DATETIME NOT NULL,hit_count INT NOT NULL DEFAULT 1,UNIQUE KEY uq_rate(bucket_key,route_key,window_start)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,actor_user_id BIGINT UNSIGNED NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(80) NOT NULL,entity_id VARCHAR(120) NULL,before_json JSON NULL,after_json JSON NULL,ip_hash BINARY(32) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_audit_created(created_at),FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_deployments(product_id BIGINT UNSIGNED NOT NULL,deployment_model_id BIGINT UNSIGNED NOT NULL,support_status VARCHAR(40) NOT NULL DEFAULT 'not_yet_verified',confidence_score DECIMAL(4,3) NOT NULL DEFAULT 0,PRIMARY KEY(product_id,deployment_model_id),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,FOREIGN KEY(deployment_model_id) REFERENCES deployment_models(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_integrations(product_id BIGINT UNSIGNED NOT NULL,integration_id BIGINT UNSIGNED NOT NULL,support_status VARCHAR(40) NOT NULL DEFAULT 'not_yet_verified',confidence_score DECIMAL(4,3) NOT NULL DEFAULT 0,PRIMARY KEY(product_id,integration_id),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,FOREIGN KEY(integration_id) REFERENCES integrations(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE consultations ADD COLUMN IF NOT EXISTS deployment_model_id BIGINT UNSIGNED NULL, ADD COLUMN IF NOT EXISTS expected_users INT NULL;
INSERT INTO deployment_models(name,slug,description) VALUES ('Public SaaS','public-saas','Vendor-hosted public SaaS'),('Private Cloud','private-cloud','Dedicated/private cloud deployment'),('Self-hosted','self-hosted','Customer-managed hosting'),('On-premise','on-premise','Customer datacenter deployment'),('Hybrid','hybrid','Mixed deployment') ON DUPLICATE KEY UPDATE description=VALUES(description);
INSERT INTO integrations(name,slug,description) VALUES ('Microsoft Entra ID','microsoft-entra-id','Microsoft Entra ID'),('Microsoft 365','microsoft-365','Microsoft 365'),('CRM','crm','CRM integration'),('API','api','General API integration') ON DUPLICATE KEY UPDATE description=VALUES(description);
INSERT INTO product_deployments(product_id,deployment_model_id,support_status,confidence_score)
SELECT p.id,d.id,'supported',0.95 FROM products p JOIN deployment_models d ON d.slug='public-saas' WHERE p.slug IN('cardiq','blinq','hihello')
ON DUPLICATE KEY UPDATE support_status=VALUES(support_status),confidence_score=VALUES(confidence_score);
INSERT INTO product_integrations(product_id,integration_id,support_status,confidence_score)
SELECT p.id,i.id,CASE WHEN p.slug='cardiq' AND i.slug='microsoft-entra-id' THEN 'not_supported' WHEN p.slug IN('blinq','hihello') AND i.slug='microsoft-entra-id' THEN 'supported' ELSE 'not_yet_verified' END,CASE WHEN i.slug='microsoft-entra-id' THEN 0.95 ELSE 0 END FROM products p JOIN integrations i WHERE p.slug IN('cardiq','blinq','hihello')
ON DUPLICATE KEY UPDATE support_status=VALUES(support_status),confidence_score=VALUES(confidence_score);
COMMIT;