-- TechSelectAI customer outcomes / case studies foundation
-- No seed data by design. Public rendering requires verified + published state.

CREATE TABLE IF NOT EXISTS customer_outcomes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(180) NOT NULL,
  title VARCHAR(220) NOT NULL,
  summary TEXT NULL,
  product_id BIGINT UNSIGNED NULL,
  category_id BIGINT UNSIGNED NULL,
  visibility_mode ENUM('anonymous','named') NOT NULL DEFAULT 'anonymous',
  customer_name VARCHAR(180) NULL,
  customer_logo_url VARCHAR(500) NULL,
  customer_name_approved TINYINT(1) NOT NULL DEFAULT 0,
  customer_logo_approved TINYINT(1) NOT NULL DEFAULT 0,
  industry VARCHAR(140) NULL,
  country VARCHAR(120) NULL,
  company_size VARCHAR(80) NULL,
  problem TEXT NOT NULL,
  requirements_text TEXT NULL,
  options_evaluated TEXT NULL,
  recommendation TEXT NULL,
  rationale TEXT NULL,
  implementation_decision TEXT NULL,
  measurable_outcome TEXT NULL,
  outcome_date DATE NULL,
  evidence_notes TEXT NULL,
  verification_status ENUM('draft','in_review','verified','rejected') NOT NULL DEFAULT 'draft',
  publication_status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  approval_notes TEXT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customer_outcomes_slug (slug),
  KEY idx_customer_outcomes_public (verification_status, publication_status, published_at),
  KEY idx_customer_outcomes_product (product_id),
  KEY idx_customer_outcomes_category (category_id),
  CONSTRAINT fk_customer_outcomes_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_customer_outcomes_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
