import React,{useEffect,useMemo,useState}from'react';
const SESSION_KEY='techselectai.activeConsultation.v1';
const ADSENSE_CLIENT=import.meta.env.VITE_ADSENSE_CLIENT||'';
const ADSENSE_PRODUCT_SLOT=import.meta.env.VITE_ADSENSE_PRODUCT_SLOT||'';

function ensureMeta(selector,attrs){let el=document.head.querySelector(selector);if(!el){el=document.createElement('meta');document.head.appendChild(el)}Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el}
function setSeo(title,description,canonical,jsonLd){
 document.title=title;
 ensureMeta('meta[name="description"]',{name:'description',content:description});
 let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;
 ensureMeta('meta[property="og:title"]',{property:'og:title',content:title});
 ensureMeta('meta[property="og:description"]',{property:'og:description',content:description});
 ensureMeta('meta[property="og:url"]',{property:'og:url',content:canonical});
 ensureMeta('meta[property="og:type"]',{property:'og:type',content:'website'});
 let s=document.getElementById('jsonld');if(s)s.remove();if(jsonLd){s=document.createElement('script');s.id='jsonld';s.type='application/ld+json';s.text=JSON.stringify(jsonLd);document.head.appendChild(s)}
}
async function api(url,options={}){const r=await fetch(url,options);const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{throw new Error(`Server returned an invalid response (${r.status})`)}if(!r.ok)throw new Error(d.message||d.error||`Request failed (${r.status})`);return d}
function loadActive(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function saveActive(v){try{sessionStorage.setItem(SESSION_KEY,JSON.stringify(v))}catch{}}
function clearActive(){try{sessionStorage.removeItem(SESSION_KEY)}catch{}}
function consideringFromUrl(){try{return new URLSearchParams(location.search).get('considering')||''}catch{return''}}
function adviceHref(name){return '/?considering='+encodeURIComponent(name)}
function fmtDate(v){if(!v)return'Not yet verified';const d=new Date(v);return Number.isNaN(d.getTime())?'Not yet verified':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function statusLabel(v){return(v||'not_yet_verified').replaceAll('_',' ')}
function compareHref(a,b){return '/compare/'+[a,b].sort().join('-vs-')}
function mandatoryGapCopy(n){return n===1?'1 mandatory gap requires review.':`${n} mandatory gaps require review.`}
function coverageCopy(r){const known=Number(r.known_fact_count)||0,total=Number(r.requirement_count)||0,pct=Number(r.evidence_coverage)||0;return `Known evidence ${known}/${total} requested criteria (${pct.toFixed(0)}%)`}

function AdSenseBlock({slot=ADSENSE_PRODUCT_SLOT}){useEffect(()=>{if(!ADSENSE_CLIENT||!slot)return;const id='techselectai-adsense-script';if(!document.getElementById(id)){const s=document.createElement('script');s.id=id;s.async=true;s.crossOrigin='anonymous';s.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(ADSENSE_CLIENT)}`;document.head.appendChild(s)}const timer=setTimeout(()=>{try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch{}},0);return()=>clearTimeout(timer)},[slot]);if(!ADSENSE_CLIENT||!slot)return null;return <aside className="ad-wrap" aria-label="Advertisement"><div className="ad-label">Advertisement</div><ins className="adsbygoogle" style={{display:'block'}} data-ad-client={ADSENSE_CLIENT} data-ad-slot={slot} data-ad-format="auto" data-full-width-responsive="true"></ins></aside>}
function ConsultancyCta({product}){return <section className="consultancy-cta"><div><div className="eyebrow">Independent software advice</div><h2>Considering {product.name} for your company?</h2><p>TechSelectAI can evaluate whether {product.name} fits your requirements, integrations, deployment model, budget and compliance needs.</p></div><a className="button-link" href={adviceHref(product.name)}>Evaluate {product.name} for my company</a></section>}
function CardIqSponsor({product}){const category=(product.category||'').toLowerCase();const relevant=product.slug!=='cardiq'&&(category.includes('digital business card')||category.includes('corporate identity'));if(!relevant)return null;return <aside className="sponsor-card"><div className="sponsor-label">Sponsored · Relevant alternative</div><div className="sponsor-body"><div><h3>CardIQ</h3><p>Corporate digital identity control with managed business cards, employee verification, signatures and identity lifecycle capabilities.</p><small>CardIQ is a Barmageyat product. Sponsorship does not affect TechSelectAI rankings, methodology or evidence scoring.</small></div><a className="secondary-link" href="/software/cardiq">Review CardIQ evidence</a></div></aside>}

function Home(){
 const[saved]=useState(()=>loadActive());const[considering]=useState(()=>consideringFromUrl());
 const initialProblem=saved?.problem||(considering?`We are considering ${considering} for our company. Help us evaluate whether it fits our requirements and identify better alternatives if appropriate.`:'');
 const[problem,setProblem]=useState(initialProblem);const[c,setC]=useState(saved?.c||null);const[msgs,setMsgs]=useState(saved?.msgs||[]);const[input,setInput]=useState('');const[extraction,setExtraction]=useState(saved?.extraction||null);const[results,setResults]=useState(saved?.results||[]);const[busy,setBusy]=useState(false);const[thinking,setThinking]=useState(false);const[processingLabel,setProcessingLabel]=useState('');const[error,setError]=useState('');
 useEffect(()=>{if(c)saveActive({problem,c,msgs,extraction,results})},[problem,c,msgs,extraction,results]);
 function reset(){clearActive();setProblem(considering?`We are considering ${considering} for our company. Help us evaluate whether it fits our requirements and identify better alternatives if appropriate.`:'');setC(null);setMsgs([]);setInput('');setExtraction(null);setResults([]);setBusy(false);setThinking(false);setProcessingLabel('');setError('');window.scrollTo({top:0,behavior:'smooth'})}
 async function start(){setBusy(true);setError('');try{const x=await api('/api/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({business_problem:problem})});setC(x);setMsgs([{role:'user',text:problem},{role:'assistant',text:'Tell me any other important requirements, integrations, deployment restrictions, languages or budget constraints.'}]);setExtraction(null);setResults([])}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function send(){if(!input.trim()||busy)return;const text=input;setInput('');setMsgs(x=>[...x,{role:'user',text}]);setBusy(true);setThinking(true);setError('');try{const x=await api(`/api/consultations/${c.public_token}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});setMsgs(v=>[...v,{role:'assistant',text:x.message}]);setExtraction(x)}catch(e){setError(e.message)}finally{setThinking(false);setBusy(false)}}
 async function confirm(){if(!extraction||busy)return;setBusy(true);setProcessingLabel('Reviewing and confirming requirements');setError('');try{await api(`/api/consultations/${c.public_token}/extractions/${extraction.extraction_run_id}/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});setMsgs(v=>[...v,{role:'assistant',text:'Requirements confirmed. I can now run the deterministic recommendation engine.'}]);setExtraction(null)}catch(e){setError(e.message)}finally{setProcessingLabel('');setBusy(false)}}
 async function recommend(){if(busy)return;setBusy(true);setProcessingLabel('Evaluating products against your requirements');setError('');try{const x=await api(`/api/consultations/${c.public_token}/recommendations`,{method:'POST'});setResults(x.recommendations||[])}catch(e){setError(e.message)}finally{setProcessingLabel('');setBusy(false)}}
 if(!c)return <main><section className="hero">{considering&&<div className="context-chip">Evaluating {considering}</div>}<div className="eyebrow">Independent software & technology advisory</div><h1>Find the right technology for your business.</h1><p>Describe what you need. TechSelectAI structures your requirements and evaluates suitable options using evidence-backed data.</p><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="We need a CRM for 60 users in Saudi Arabia with Arabic and WhatsApp"/><button onClick={start} disabled={busy||problem.trim().length<5}>{busy?'Starting…':'Start free consultation'}</button>{error&&<div className="notice">{error}</div>}</section></main>;
 return <main><section className="consult"><div className="consult-head"><div><div className="eyebrow">AI-guided consultation</div><h1>Define what your business needs</h1></div><button className="secondary" onClick={reset} disabled={busy}>Start new consultation</button></div><div className="messages">{msgs.map((m,i)=><div key={i} className={'msg '+m.role}>{m.text}</div>)}{thinking&&<div className="msg assistant thinking" role="status" aria-live="polite"><span>Analyzing your requirements</span><span className="thinking-dots" aria-hidden="true"><i></i><i></i><i></i></span></div>}{processingLabel&&<div className="msg assistant thinking" role="status" aria-live="polite"><span>{processingLabel}</span><span className="thinking-dots" aria-hidden="true"><i></i><i></i><i></i></span></div>}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!busy&&send()} placeholder={thinking?'AI is analyzing your requirements…':processingLabel?'Processing your consultation…':'Add requirements or constraints…'} disabled={busy}/><button onClick={send} disabled={busy||!input.trim()}>{thinking?'Thinking…':'Send'}</button></div>{extraction&&<div className="review"><h3>Review extracted requirements</h3>{extraction.extraction?.category_slug&&<p><b>Category:</b> {extraction.extraction.category_slug.replaceAll('-',' ')}</p>}{(extraction.extraction?.requirements||[]).map((r,i)=><p key={i}><b>{r.priority.replaceAll('_',' ')}:</b> {r.text}{r.capability_slug?` · ${r.capability_slug.replaceAll('-',' ')}`:''}</p>)}<button onClick={confirm} disabled={busy}>{processingLabel==='Reviewing and confirming requirements'?'Reviewing…':'Confirm these requirements'}</button></div>}<div className="actions"><button onClick={recommend} disabled={busy}>{processingLabel==='Evaluating products against your requirements'?'Evaluating…':'Find best matches'}</button></div>{error&&<div className="notice">{error}</div>}</section>{results.length>0&&<section><h2>Recommendations</h2><p>Fit and evidence confidence are separate. Unknown does not mean unsupported. Evidence coverage shows how many of your requested criteria currently have a known product fact rather than an unknown/not-yet-verified status.</p><div className="grid">{results.map(r=><div className="card" key={r.product.id}><small>#{r.rank} · {statusLabel(r.status)}</small><h3>{r.product.name}</h3><p><b>{Number(r.overall).toFixed(0)}%</b> overall fit · {Number(r.evidence).toFixed(0)}% evidence confidence</p><p>Functional {Number(r.functional).toFixed(0)}% · Must-have {Number(r.mandatory).toFixed(0)}%</p><p><b>{coverageCopy(r)}</b> · {statusLabel(r.evidence_coverage_label)} coverage</p>{r.evidence_warning&&<p className="warning">{r.evidence_warning}</p>}{r.mandatory_gaps>0&&<p className="warning">{mandatoryGapCopy(r.mandatory_gaps)}</p>}<a href={'/software/'+r.product.slug}>Review evidence</a></div>)}</div></section>}</main>
}

function Software(){const[d,setD]=useState([]);useEffect(()=>{setSeo('Software Directory | TechSelectAI','Explore evidence-backed software profiles and compare verified capabilities.','https://techselectai.com/software',{'@context':'https://schema.org','@type':'CollectionPage',name:'TechSelectAI Software Directory',url:'https://techselectai.com/software'});api('/api/software').then(x=>setD(x.products||[])).catch(()=>setD([]))},[]);return <main><h1>Software explorer</h1><p>Evidence-backed software profiles with explicit support status, confidence and source transparency.</p><div className="grid">{d.map(p=><a className="card" href={'/software/'+p.slug} key={p.id}><small>{p.category} · {p.vendor}</small><h3>{p.name}</h3><p>{p.short_description}</p></a>)}</div></main>}

function Product({slug}){
 const[d,setD]=useState(null);const[all,setAll]=useState([]);const[error,setError]=useState('');
 useEffect(()=>{setError('');Promise.all([api('/api/software/'+slug),api('/api/software')]).then(([x,list])=>{const p=x.product;setD(p);setAll(list.products||[]);const desc=p.short_description||`Review ${p.name} capabilities, limitations and evidence.`;setSeo(`${p.name} Review, Capabilities, Limitations & Evidence | TechSelectAI`,desc,`https://techselectai.com/software/${slug}`,{'@context':'https://schema.org','@graph':[{'@type':'SoftwareApplication',name:p.name,applicationCategory:p.category,url:`https://techselectai.com/software/${slug}`,description:desc},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Software',item:'https://techselectai.com/software'},{'@type':'ListItem',position:2,name:p.name,item:`https://techselectai.com/software/${slug}`}]}]})}).catch(e=>setError(e.message))},[slug]);
 const supported=useMemo(()=>d?.capabilities?.filter(c=>c.support_status==='supported')||[],[d]);
 const review=useMemo(()=>d?.capabilities?.filter(c=>c.support_status!=='supported')||[],[d]);
 const alternatives=useMemo(()=>all.filter(p=>p.slug!==slug&&p.category===d?.category).slice(0,4),[all,d,slug]);
 if(error)return <main><div className="notice"><b>Unable to load product details.</b><br/>{error}<br/><a href="/">Return to your consultation</a></div></main>;
 if(!d)return <main><div className="loading-state">Loading product details…</div></main>;
 return <main className="product-page">
  <small><a href="/software">Software</a> · {d.category} · {d.vendor}</small><h1>{d.name}</h1><p className="product-summary">{d.short_description}</p>
  <section><h2>What TechSelectAI currently verifies</h2><p>{supported.length} capability{supported.length===1?' is':'ies are'} currently recorded as supported. Support status is based on the evidence available to TechSelectAI and may vary by edition, configuration or deployment.</p>{supported.length>0&&<div className="grid">{supported.slice(0,6).map(c=><a className="card" href={'/capabilities/'+c.slug} key={c.slug}><small>{c.module}</small><h3>{c.name}</h3><p>{Math.round((Number(c.confidence_score)||0)*100)}% evidence confidence</p></a>)}</div>}</section>
  <section><h2>Capabilities and evidence status</h2><table><thead><tr><th>Capability</th><th>Status</th><th>Confidence</th><th>Last verified</th></tr></thead><tbody>{d.capabilities.map(c=><tr key={c.slug}><td><a href={'/capabilities/'+c.slug}>{c.name}</a><br/><small>{c.module}</small></td><td>{statusLabel(c.support_status)}</td><td>{Math.round((Number(c.confidence_score)||0)*100)}%</td><td>{fmtDate(c.last_verified_at)}</td></tr>)}</tbody></table></section>
  {review.length>0&&<section><h2>Limitations, gaps and items to confirm</h2><div className="grid">{review.map(c=><div className="card" key={c.slug}><small>{statusLabel(c.support_status)}</small><h3>{c.name}</h3><p>{c.limitations||'Support is not fully verified in the current TechSelectAI evidence set.'}</p></div>)}</div></section>}
  <section><h2>Questions to ask {d.vendor||d.name}</h2><div className="grid">{(review.length?review.slice(0,4):d.capabilities.slice(0,3)).map(c=><div className="card" key={'q-'+c.slug}><h3>{c.name}</h3><p>Confirm whether this capability is included in the edition you are considering, whether extra configuration or add-ons are required, and what limitations apply to your deployment.</p></div>)}</div></section>
  <section><h2>Evidence sources</h2>{d.evidence.length?d.evidence.map((e,i)=><p key={i}><a href={e.source_url} target="_blank" rel="noreferrer">{e.source_title}</a> · {statusLabel(e.verification_status)} · checked {fmtDate(e.checked_at)}</p>):<p className="muted">No published evidence sources are available yet.</p>}</section>
  {alternatives.length>0&&<section><h2>Related alternatives and comparisons</h2><div className="grid">{alternatives.map(p=><div className="card" key={p.slug}><h3><a href={'/software/'+p.slug}>{p.name}</a></h3><p>{p.short_description}</p><a href={compareHref(slug,p.slug)}>Compare {d.name} vs {p.name}</a></div>)}</div></section>}
  <ConsultancyCta product={d}/><CardIqSponsor product={d}/><AdSenseBlock/>
 </main>
}

function Capability({slug}){
 const[d,setD]=useState(null);const[error,setError]=useState('');
 useEffect(()=>{api('/api/capabilities/'+slug).then(x=>{setD(x.capability);const c=x.capability;if(c)setSeo(`${c.name} Software Support Comparison | TechSelectAI`,c.description||`Compare software support and evidence confidence for ${c.name}.`,`https://techselectai.com/capabilities/${slug}`,{'@context':'https://schema.org','@graph':[{'@type':'WebPage',name:`${c.name} software capability comparison`,description:c.description||''},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Software',item:'https://techselectai.com/software'},{'@type':'ListItem',position:2,name:c.name,item:`https://techselectai.com/capabilities/${slug}`}]}]})}).catch(e=>setError(e.message))},[slug]);
 if(error)return <main><div className="notice">Unable to load capability: {error}</div></main>;if(!d)return <main>Loading…</main>;
 return <main><small>{d.category} · {d.module}</small><h1>{d.name}</h1><p>{d.description}</p><p>Support status and evidence confidence are separate. “Not yet verified” means TechSelectAI does not currently have enough evidence; it does not mean the product lacks the capability.</p><div className="grid">{d.products.map(p=><a className="card" href={'/software/'+p.slug} key={p.slug}><h3>{p.name}</h3><p><b>{statusLabel(p.support_status)}</b> · {Math.round((Number(p.confidence_score)||0)*100)}% confidence</p>{p.limitations&&<small>{p.limitations}</small>}</a>)}</div><section className="consultancy-cta"><div><div className="eyebrow">Need help choosing?</div><h2>Make this capability part of your requirements</h2><p>TechSelectAI can compare products against your full business context instead of this capability alone.</p></div><a className="button-link" href={adviceHref(d.name)}>Get independent software advice</a></section></main>
}

function Compare({pair}){const[d,setD]=useState(null);const[error,setError]=useState('');useEffect(()=>{api('/api/compare/'+pair).then(x=>{if(x.canonical&&x.canonical!==pair){location.replace('/compare/'+x.canonical);return}setD(x);if(x.products?.length===2){const a=x.products[0],b=x.products[1];setSeo(`${a.name} vs ${b.name}: Evidence-Backed Comparison | TechSelectAI`,`Compare ${a.name} and ${b.name} capability support using TechSelectAI evidence.`,`https://techselectai.com/compare/${x.canonical}`,{'@context':'https://schema.org','@type':'WebPage',name:`${a.name} vs ${b.name}`,url:`https://techselectai.com/compare/${x.canonical}`})}}).catch(e=>setError(e.message))},[pair]);if(error)return <main><div className="notice">Unable to load comparison: {error}</div></main>;if(!d)return <main>Loading…</main>;return <main><h1>{d.products[0].name} vs {d.products[1].name}</h1><p>Evidence-backed capability comparison. Unknown means not yet verified; it does not mean unsupported.</p><table><thead><tr><th>Capability</th><th>Product</th><th>Status</th></tr></thead><tbody>{d.facts.map((f,i)=><tr key={i}><td><a href={'/capabilities/'+f.slug}>{f.module} · {f.name}</a></td><td>{d.products.find(p=>p.id==f.product_id)?.name}</td><td>{statusLabel(f.support_status)}</td></tr>)}</tbody></table><section className="consultancy-cta"><div><div className="eyebrow">Independent software advice</div><h2>Need a recommendation beyond a two-product comparison?</h2><p>Tell TechSelectAI your requirements and let the deterministic engine evaluate all currently covered products.</p></div><a className="button-link" href="/">Start free consultation</a></section></main>}

export default function App(){const path=location.pathname.split('/').filter(Boolean);let page=<Home/>;if(path[0]==='software'&&!path[1])page=<Software/>;else if(path[0]==='software'&&path[1])page=<Product slug={path[1]}/>;else if(path[0]==='capabilities'&&path[1])page=<Capability slug={path[1]}/>;else if(path[0]==='compare'&&path[1])page=<Compare pair={path[1]}/>;return <><header><a href="/" className="brand">TechSelectAI</a><nav><a href="/software">Software</a><a href="/methodology">Methodology</a><a href="/">Get Advice</a></nav></header>{page}</>}
