import React,{useEffect,useState}from'react';
function setSeo(title,description,canonical,jsonLd){document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('link[rel="canonical"]')?.setAttribute('href',canonical);let s=document.getElementById('jsonld');if(s)s.remove();if(jsonLd){s=document.createElement('script');s.id='jsonld';s.type='application/ld+json';s.text=JSON.stringify(jsonLd);document.head.appendChild(s)}}
async function api(url,options={}){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}

function Home(){
 const[problem,setProblem]=useState('');const[c,setC]=useState(null);const[msgs,setMsgs]=useState([]);const[input,setInput]=useState('');const[extraction,setExtraction]=useState(null);const[results,setResults]=useState([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 async function start(){setBusy(true);setError('');try{const x=await api('/api/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({business_problem:problem})});setC(x);setMsgs([{role:'user',text:problem},{role:'assistant',text:'Tell me any other important requirements, integrations, deployment restrictions, languages or budget constraints.'}])}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function send(){if(!input.trim())return;const text=input;setInput('');setMsgs(x=>[...x,{role:'user',text}]);setBusy(true);setError('');try{const x=await api(`/api/consultations/${c.public_token}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});setMsgs(v=>[...v,{role:'assistant',text:x.message}]);setExtraction(x)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function confirm(){if(!extraction)return;setBusy(true);setError('');try{await api(`/api/consultations/${c.public_token}/extractions/${extraction.extraction_run_id}/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});setMsgs(v=>[...v,{role:'assistant',text:'Requirements confirmed. I can now run the deterministic recommendation engine.'}]);setExtraction(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function recommend(){setBusy(true);setError('');try{const x=await api(`/api/consultations/${c.public_token}/recommendations`,{method:'POST'});setResults(x.recommendations||[])}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!c)return <main><section className="hero"><div className="eyebrow">Independent software & technology advisory</div><h1>Find the right technology for your business.</h1><p>Describe what you need. TechSelectAI structures your requirements and evaluates suitable options using evidence-backed data.</p><textarea value={problem} onChange={e=>setProblem(e.target.value)} placeholder="We need a CRM for 60 users in Saudi Arabia with Arabic and WhatsApp"/><button onClick={start} disabled={busy||problem.trim().length<5}>{busy?'Starting…':'Start free consultation'}</button>{error&&<div className="notice">{error}</div>}</section></main>;
 return <main><section className="consult"><div className="eyebrow">AI-guided consultation</div><h1>Define what your business needs</h1><div className="messages">{msgs.map((m,i)=><div key={i} className={'msg '+m.role}>{m.text}</div>)}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Add requirements or constraints…"/><button onClick={send} disabled={busy}>Send</button></div>{extraction&&<div className="review"><h3>Review extracted requirements</h3>{extraction.extraction?.category_slug&&<p><b>Category:</b> {extraction.extraction.category_slug.replaceAll('-',' ')}</p>}{(extraction.extraction?.requirements||[]).map((r,i)=><p key={i}><b>{r.priority.replaceAll('_',' ')}:</b> {r.text}{r.capability_slug?` · ${r.capability_slug.replaceAll('-',' ')}`:''}</p>)}<button onClick={confirm} disabled={busy}>Confirm these requirements</button></div>}<div className="actions"><button onClick={recommend} disabled={busy}>Find best matches</button></div>{error&&<div className="notice">{error}</div>}</section>{results.length>0&&<section><h2>Recommendations</h2><p>Fit and evidence confidence are separate. Unknown does not mean unsupported.</p><div className="grid">{results.map(r=><div className="card" key={r.product.id}><small>#{r.rank} · {r.status.replaceAll('_',' ')}</small><h3>{r.product.name}</h3><p><b>{Number(r.overall).toFixed(0)}%</b> overall fit · {Number(r.evidence).toFixed(0)}% evidence confidence</p><p>Functional {Number(r.functional).toFixed(0)}% · Must-have {Number(r.mandatory).toFixed(0)}%</p>{r.mandatory_gaps>0&&<p className="warning">{r.mandatory_gaps} mandatory gap(s) require review.</p>}<a href={'/software/'+r.product.slug}>Review evidence</a></div>)}</div></section>}</main>
}
function Software(){const[d,setD]=useState([]);useEffect(()=>{setSeo('Software Directory | TechSelectAI','Explore evidence-backed software profiles.','https://techselectai.com/software');fetch('/api/software').then(r=>r.json()).then(x=>setD(x.products||[]))},[]);return <main><h1>Software explorer</h1><div className="grid">{d.map(p=><a className="card" href={'/software/'+p.slug} key={p.id}><small>{p.category} · {p.vendor}</small><h3>{p.name}</h3><p>{p.short_description}</p></a>)}</div></main>}
function Product({slug}){const[d,setD]=useState(null);useEffect(()=>{fetch('/api/software/'+slug).then(r=>r.json()).then(x=>{setD(x.product);if(x.product)setSeo(`${x.product.name} Review, Capabilities & Evidence | TechSelectAI`,x.product.short_description||`Review ${x.product.name}.`,`https://techselectai.com/software/${slug}`,{'@context':'https://schema.org','@type':'SoftwareApplication',name:x.product.name,applicationCategory:x.product.category,url:`https://techselectai.com/software/${slug}`})})},[slug]);if(!d)return <main>Loading…</main>;return <main><small>{d.category} · {d.vendor}</small><h1>{d.name}</h1><p>{d.short_description}</p><h2>Capabilities</h2><table><tbody>{d.capabilities.map((c,i)=><tr key={i}><td><a href={'/capabilities/'+c.slug}>{c.name}</a></td><td>{c.support_status.replaceAll('_',' ')}</td><td>{Math.round((Number(c.confidence_score)||0)*100)}%</td></tr>)}</tbody></table><h2>Evidence</h2>{d.evidence.map((e,i)=><p key={i}><a href={e.source_url} target="_blank" rel="noreferrer">{e.source_title}</a> · {e.verification_status}</p>)}</main>}
function Capability({slug}){const[d,setD]=useState(null);useEffect(()=>{fetch('/api/capabilities/'+slug).then(r=>r.json()).then(x=>{setD(x.capability);if(x.capability)setSeo(`${x.capability.name} Software Capability Comparison | TechSelectAI`,x.capability.description||`Compare ${x.capability.name} support.`,`https://techselectai.com/capabilities/${slug}`)})},[slug]);if(!d)return <main>Loading…</main>;return <main><small>{d.category} · {d.module}</small><h1>{d.name}</h1><p>{d.description}</p><div className="grid">{d.products.map(p=><a className="card" href={'/software/'+p.slug} key={p.slug}><h3>{p.name}</h3><p>{p.support_status.replaceAll('_',' ')}</p></a>)}</div></main>}
function Compare({pair}){const[d,setD]=useState(null);useEffect(()=>{fetch('/api/compare/'+pair).then(r=>r.json()).then(x=>{if(x.canonical&&x.canonical!==pair){location.replace('/compare/'+x.canonical);return}setD(x);if(x.products?.length===2)setSeo(`${x.products[0].name} vs ${x.products[1].name} | TechSelectAI`,`Evidence-backed comparison of ${x.products[0].name} and ${x.products[1].name}.`,`https://techselectai.com/compare/${x.canonical}`)})},[pair]);if(!d)return <main>Loading…</main>;return <main><h1>{d.products[0].name} vs {d.products[1].name}</h1><p>Unknown means not yet verified; it does not mean unsupported.</p><table><tbody>{d.facts.map((f,i)=><tr key={i}><td>{f.module} · {f.name}</td><td>{d.products.find(p=>p.id==f.product_id)?.name}</td><td>{f.support_status.replaceAll('_',' ')}</td></tr>)}</tbody></table></main>}
export default function App(){const path=location.pathname.split('/').filter(Boolean);let page=<Home/>;if(path[0]==='software'&&!path[1])page=<Software/>;else if(path[0]==='software'&&path[1])page=<Product slug={path[1]}/>;else if(path[0]==='capabilities'&&path[1])page=<Capability slug={path[1]}/>;else if(path[0]==='compare'&&path[1])page=<Compare pair={path[1]}/>;return <><header><a href="/" className="brand">TechSelectAI</a><nav><a href="/software">Software</a><a href="/methodology">Methodology</a><a href="/">Get Advice</a></nav></header>{page}</>}
