const SESSION_KEY='techselectai.activeConsultation.v1';
const CTA_ID='techselectai-save-consultation';

function readActive(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function ensureStyle(){if(document.getElementById('techselectai-save-style'))return;const s=document.createElement('style');s.id='techselectai-save-style';s.textContent=`.ts-save-consultation{margin:20px 0;padding:18px 20px;border:1px solid #d7e5ee;border-radius:16px;background:#f8fbfd;color:#172033}.ts-save-consultation h3{margin:0 0 6px;font-size:18px}.ts-save-consultation p{margin:0;color:#64748b;line-height:1.5}.ts-save-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.ts-save-actions a{display:inline-flex;align-items:center;justify-content:center;padding:10px 14px;border-radius:10px;text-decoration:none;font-weight:700}.ts-save-actions .primary{background:#123b67;color:#fff}.ts-save-actions .secondary{border:1px solid #cbd5e1;color:#123b67;background:#fff}.ts-save-ok{border-color:#bbdfc6;background:#f3fbf5}.ts-save-ok a{color:#123b67;font-weight:700}@media(max-width:560px){.ts-save-actions a{flex:1 1 140px}}`;document.head.appendChild(s)}
function recommendationSection(){return [...document.querySelectorAll('section')].find(s=>s.querySelector(':scope > h2')?.textContent?.trim()==='Recommendations')||null}
function remove(){document.getElementById(CTA_ID)?.remove()}
function renderSignedOut(host){let el=document.getElementById(CTA_ID);if(!el){el=document.createElement('aside');el.id=CTA_ID;host.appendChild(el)}el.className='ts-save-consultation';el.innerHTML='<h3>Save this consultation</h3><p>Create a free account or sign in to keep these recommendations and reopen this software search later.</p><div class="ts-save-actions"><a class="primary" href="/register?next=%2F">Create account</a><a class="secondary" href="/login?next=%2F">Log in</a></div>'}
function renderSignedIn(host){let el=document.getElementById(CTA_ID);if(!el){el=document.createElement('aside');el.id=CTA_ID;host.appendChild(el)}el.className='ts-save-consultation ts-save-ok';el.innerHTML='<h3>Saved to your account</h3><p>Your consultation is connected to your TechSelectAI account.</p><div class="ts-save-actions"><a href="/my-consultations">View My Consultations</a></div>'}
async function refresh(){const active=readActive();const host=recommendationSection();if(!host||!active?.c||!(active.results?.length>0)){remove();return}ensureStyle();try{const r=await fetch('/api/auth/csrf',{credentials:'same-origin'});if(!r.ok){renderSignedOut(host);return}const d=await r.json();d?.user?renderSignedIn(host):renderSignedOut(host)}catch{renderSignedOut(host)}}
let last='';function tick(){const a=readActive();const key=JSON.stringify([location.pathname,!!a?.c,a?.results?.length||0,!!document.getElementById(CTA_ID)]);if(key!==last){last=key;refresh()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{tick();setInterval(tick,700)},{once:true});else{tick();setInterval(tick,700)}
