const SESSION_KEY='techselectai.activeConsultation.v1';
let activeToken='';let loading=false;
function readActive(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function csrf(){const m=document.cookie.match(/(?:^|; )techselect_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):''}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function style(){if(document.getElementById('consultation-context-style'))return;const s=document.createElement('style');s.id='consultation-context-style';s.textContent=`.ts-context{margin:16px 0 20px;border:1px solid #dce7ee;border-radius:14px;background:#f8fbfd;overflow:hidden}.ts-context summary{cursor:pointer;padding:14px 16px;font-weight:700;color:#173d63}.ts-context .ts-context-body{padding:0 16px 16px}.ts-context-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ts-context label{font-size:12px;color:#607286;display:block}.ts-context input,.ts-context select{width:100%;box-sizing:border-box;margin-top:5px;padding:10px;border:1px solid #cbd8e1;border-radius:9px;background:#fff;color:#172033}.ts-context-actions{display:flex;align-items:center;gap:10px;margin-top:12px}.ts-context button{padding:9px 14px;border-radius:9px}.ts-context-status{font-size:12px;color:#64748b}.ts-context-note{margin:0 0 12px;color:#64748b;font-size:12px}@media(max-width:850px){.ts-context-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.ts-context-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function load(token,box){loading=true;try{const r=await fetch(`/api/consultations/${token}/context`,{credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load context');const c=d.context||{};box.querySelector('[name=country_code]').value=c.country_code||'';box.querySelector('[name=company_size_band]').value=c.company_size_band||'';box.querySelector('[name=expected_users]').value=c.expected_users??'';const ind=box.querySelector('[name=industry_id]');ind.innerHTML='<option value="">Prefer not to say</option>'+((d.industries||[]).map(x=>`<option value="${Number(x.id)}">${esc(x.name)}</option>`).join(''));ind.value=c.industry_id??''}catch(e){box.querySelector('.ts-context-status').textContent='Context is optional. You can continue without it.'}finally{loading=false}}
async function save(token,box){const status=box.querySelector('.ts-context-status');status.textContent='Saving…';const body={country_code:box.querySelector('[name=country_code]').value.trim(),industry_id:box.querySelector('[name=industry_id]').value,company_size_band:box.querySelector('[name=company_size_band]').value,expected_users:box.querySelector('[name=expected_users]').value};try{const headers={'Content-Type':'application/json'};const t=csrf();if(t)headers['X-CSRF-Token']=t;const r=await fetch(`/api/consultations/${token}/context`,{method:'PUT',credentials:'same-origin',headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save context');status.textContent='Saved';setTimeout(()=>{if(status.textContent==='Saved')status.textContent='Optional — improves relevance and analytics'},1800)}catch(e){status.textContent='Could not save. You can continue without it.'}}
function build(token){style();const d=document.createElement('details');d.className='ts-context';d.dataset.token=token;d.innerHTML=`<summary>Company context <span style="font-weight:400;color:#64748b">(optional)</span></summary><div class="ts-context-body"><p class="ts-context-note">A few details can improve regional relevance and help TechSelectAI understand business software demand. None of these fields is required.</p><div class="ts-context-grid"><label>Country code<input name="country_code" maxlength="2" placeholder="SA, EG, AE"></label><label>Industry<select name="industry_id"><option value="">Prefer not to say</option></select></label><label>Company size<select name="company_size_band"><option value="">Prefer not to say</option><option>1-49</option><option>50-199</option><option>200-499</option><option>500-999</option><option>1000+</option></select></label><label>Expected users<input name="expected_users" type="number" min="1" max="10000000" placeholder="e.g. 250"></label></div><div class="ts-context-actions"><button type="button" class="secondary ts-context-save">Save context</button><span class="ts-context-status">Optional — improves relevance and analytics</span></div></div>`;d.querySelector('.ts-context-save').addEventListener('click',()=>save(token,d));return d}
function sync(){const a=readActive();const token=a?.c?.public_token||'';const host=document.querySelector('.consult');const old=document.querySelector('.ts-context');if(!token||!host){if(old)old.remove();activeToken='';return}if(old&&old.dataset.token===token)return;if(old)old.remove();activeToken=token;const box=build(token);const head=host.querySelector('.consult-head');if(head)head.insertAdjacentElement('afterend',box);else host.prepend(box);load(token,box)}
const obs=new MutationObserver(sync);function init(){sync();obs.observe(document.documentElement,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
