import React,{useEffect,useState}from'react';
import{Helmet}from'react-helmet-async';
import{Link,Navigate,useParams}from'react-router-dom';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const SITE='https://techselectai.com';
function useJson(url){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{fetch(url).then(r=>{if(!r.ok)throw new Error('Not found');return r.json()}).then(setData).catch(e=>setError(e.message))},[url]);return{data,error}}
export function SoftwareList(){const{data,error}=useJson(`${API}/api/public/software`);return <main className="card" style={{maxWidth:1000,margin:'40px auto',padding:32}}><Helmet><title>Software Directory | TechSelectAI</title><meta name="description" content="Explore evidence-backed software profiles on TechSelectAI."/><link rel="canonical" href={`${SITE}/software`}/></Helmet><p className="eyebrow">SOFTWARE DIRECTORY</p><h1>Evidence-backed software profiles</h1>{error&&<p>{error}</p>}{data?.products?.map(p=><p key={p.slug}><Link to={`/software/${p.slug}`}><strong>{p.name}</strong></Link> · {p.vendor_name||'Vendor'} · {p.category_name||'Category'}</p>)}</main>}
export function ProductPage(){const{slug}=useParams();const{data,error}=useJson(`${API}/api/public/software/${slug}`);if(error)return <main className="card" style={{margin:40,padding:30}}>Product not found.</main>;if(!data)return null;const p=data.product;const desc=p.short_description||`Review ${p.name} capabilities and evidence on TechSelectAI.`;const jsonLd={"@context":"https://schema.org","@type":"SoftwareApplication",name:p.name,description:desc,applicationCategory:p.category_name,url:`${SITE}/software/${p.slug}`,publisher:{"@type":"Organization",name:p.vendor_name}};return <main className="card" style={{maxWidth:1000,margin:'40px auto',padding:32}}><Helmet><title>{p.name} Review, Capabilities & Evidence | TechSelectAI</title><meta name="description" content={desc}/><link rel="canonical" href={`${SITE}/software/${p.slug}`}/><meta property="og:title" content={`${p.name} — TechSelectAI`}/><meta property="og:description" content={desc}/><script type="application/ld+json">{JSON.stringify(jsonLd)}</script></Helmet><p className="eyebrow">{p.category_name}</p><h1>{p.name}</h1><p>{desc}</p><h2>Capabilities</h2>{data.capabilities.map(c=><p key={c.slug}><Link to={`/capabilities/${c.slug}`}>{c.name}</Link> · {c.support_status.replaceAll('_',' ')}</p>)}<h2>Evidence</h2>{data.evidence.map((e,i)=><p key={i}><a href={e.source_url} target="_blank" rel="noreferrer">{e.source_title}</a> · {e.verification_status}</p>)}</main>}
export function CapabilityPage(){const{slug}=useParams();const{data,error}=useJson(`${API}/api/public/capabilities/${slug}`);if(error)return <main className="card" style={{margin:40,padding:30}}>Capability not found.</main>;if(!data)return null;const c=data.capability;const desc=c.description||`Compare software with documented ${c.name} support.`;return <main className="card" style={{maxWidth:1000,margin:'40px auto',padding:32}}><Helmet><title>{c.name} Software Capability Comparison | TechSelectAI</title><meta name="description" content={desc}/><link rel="canonical" href={`${SITE}/capabilities/${c.slug}`}/></Helmet><p className="eyebrow">CAPABILITY</p><h1>{c.name}</h1><p>{desc}</p>{data.products.map(p=><p key={p.slug}><Link to={`/software/${p.slug}`}><strong>{p.name}</strong></Link> · {p.support_status.replaceAll('_',' ')}</p>)}</main>}
export function ComparePage(){const{pair}=useParams();const{data,error}=useJson(`${API}/api/public/compare/${pair}`);if(error)return <main className="card" style={{margin:40,padding:30}}>Comparison not found.</main>;if(!data)return null;if(data.redirect)return <Navigate replace to={`/compare/${data.canonical_pair}`}/>;const[p1,p2]=data.products.sort((a,b)=>a.slug.localeCompare(b.slug));const title=`${p1.name} vs ${p2.name}: Feature Comparison`;const desc=`Compare ${p1.name} and ${p2.name} using documented capability data and explicit unknown states.`;const grouped={};data.capabilities.forEach(r=>{grouped[r.capability_slug]??={name:r.capability_name,module:r.module_name};grouped[r.capability_slug][r.product_slug]=r.support_status});return <main className="card" style={{maxWidth:1100,margin:'40px auto',padding:32}}><Helmet><title>{title} | TechSelectAI</title><meta name="description" content={desc}/><link rel="canonical" href={`${SITE}/compare/${data.canonical_pair}`}/></Helmet><p className="eyebrow">COMPARISON</p><h1>{p1.name} vs {p2.name}</h1><p>{desc}</p><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th>Capability</th><th>{p1.name}</th><th>{p2.name}</th></tr></thead><tbody>{Object.entries(grouped).map(([slug,row])=><tr key={slug}><td><Link to={`/capabilities/${slug}`}>{row.name}</Link></td><td>{row[p1.slug]?.replaceAll('_',' ')||'not yet verified'}</td><td>{row[p2.slug]?.replaceAll('_',' ')||'not yet verified'}</td></tr>)}</tbody></table></main>}
