<?php
require_once __DIR__.'/../app/lib/Db.php';require_once __DIR__.'/../app/lib/Security.php';require_once __DIR__.'/../app/lib/PublicReviewAdminService.php';$config=require __DIR__.'/../app/config.php';$pdo=Db::pdo();Security::start();$u=Security::requireRole(['admin','data_editor','reviewer','super_admin']);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';function out($d,int $s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function body(){return json_decode(file_get_contents('php://input'),true)?:[];}function pri_role($u){return in_array($u['role'],['reviewer','super_admin','admin'],true);}
if($method!=='GET'){Security::sameOrigin($config);Security::requireCsrf();Security::rateLimit($pdo,'admin-write',60,60);}
if($path==='/api/admin/summary'&&$method==='GET'){$counts=[];foreach(['products','evidence_sources','users','consultations'] as $t)$counts[$t]=(int)$pdo->query("SELECT COUNT(*) FROM {$t}")->fetchColumn();$counts['unverified_evidence']=(int)$pdo->query("SELECT COUNT(*) FROM evidence_sources WHERE verification_status<>'verified'")->fetchColumn();try{$counts['pri_sources']=(int)$pdo->query("SELECT COUNT(*) FROM public_review_sources")->fetchColumn();$counts['pri_pending_review']=(int)$pdo->query("SELECT COUNT(*) FROM public_review_sources WHERE access_policy='pending_review'")->fetchColumn();}catch(Throwable $e){}out($counts);}
if($path==='/api/admin/products'&&$method==='GET'){$q=$pdo->query("SELECT p.id,p.name,p.slug,p.status,p.last_reviewed_at,v.name vendor,c.name category FROM products p LEFT JOIN vendors v ON v.id=p.vendor_id LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.name");out(['products'=>$q->fetchAll()]);}
if(preg_match('#^/api/admin/products/(\d+)$#',$path,$m)&&$method==='PATCH'){$id=(int)$m[1];$before=$pdo->prepare("SELECT id,name,short_description,status,website_url,last_reviewed_at FROM products WHERE id=?");$before->execute([$id]);$old=$before->fetch();if(!$old)out(['error'=>'not_found'],404);$b=body();$status=$b['status']??$old['status'];if(!in_array($status,['active','draft','archived'],true))out(['error'=>'invalid_status'],422);if($status==='active'&&!pri_role($u))out(['error'=>'reviewer_required_to_activate'],403);$name=trim($b['name']??$old['name']);$desc=$b['short_description']??$old['short_description'];$url=$b['website_url']??$old['website_url'];$pdo->prepare("UPDATE products SET name=?,short_description=?,website_url=?,status=?,last_reviewed_at=CASE WHEN ?='active' THEN NOW() ELSE last_reviewed_at END WHERE id=?")->execute([$name,$desc,$url,$status,$status,$id]);$after=$pdo->prepare("SELECT id,name,short_description,status,website_url,last_reviewed_at FROM products WHERE id=?");$after->execute([$id]);$new=$after->fetch();Security::audit($pdo,(int)$u['id'],'PRODUCT_UPDATE','product',(string)$id,$old,$new);out(['product'=>$new]);}
if($path==='/api/admin/evidence'&&$method==='GET'){$q=$pdo->query("SELECT e.id,p.name product,e.source_title,e.source_url,e.source_type,e.verification_status,e.confidence,e.checked_at FROM evidence_sources e JOIN products p ON p.id=e.product_id ORDER BY e.checked_at DESC");out(['evidence'=>$q->fetchAll()]);}
if(preg_match('#^/api/admin/evidence/(\d+)$#',$path,$m)&&$method==='PATCH'){$id=(int)$m[1];$st=$pdo->prepare("SELECT * FROM evidence_sources WHERE id=?");$st->execute([$id]);$old=$st->fetch();if(!$old)out(['error'=>'not_found'],404);if(!pri_role($u))out(['error'=>'reviewer_required'],403);$b=body();$status=$b['verification_status']??$old['verification_status'];if(!in_array($status,['verified','unverified','outdated','broken','disputed','superseded','placeholder'],true))out(['error'=>'invalid_evidence_status'],422);$confidence=$b['confidence']??$old['confidence'];$notes=$b['notes']??$old['notes'];$pdo->prepare("UPDATE evidence_sources SET verification_status=?,confidence=?,notes=?,checked_at=NOW() WHERE id=?")->execute([$status,$confidence,$notes,$id]);$st->execute([$id]);$new=$st->fetch();Security::audit($pdo,(int)$u['id'],'EVIDENCE_UPDATE','evidence',(string)$id,$old,$new);out(['evidence'=>$new]);}
if($path==='/api/admin/pri/sources'&&$method==='GET'){try{$pid=isset($_GET['product_id'])?(int)$_GET['product_id']:null;out(['sources'=>PublicReviewAdminService::listSources($pdo,$pid)]);}catch(Throwable $e){out(['error'=>'pri_unavailable','detail'=>$e->getMessage()],503);}}
if($path==='/api/admin/pri/sources'&&$method==='POST'){if(!pri_role($u))out(['error'=>'reviewer_required'],403);try{$new=PublicReviewAdminService::addSource($pdo,body());Security::audit($pdo,(int)$u['id'],'PRI_SOURCE_CREATE','public_review_source',(string)$new['id'],null,$new);out(['source'=>$new],201);}catch(Throwable $e){out(['error'=>$e->getMessage()],422);}}
if(preg_match('#^/api/admin/pri/sources/(\d+)$#',$path,$m)&&$method==='PATCH'){if(!pri_role($u))out(['error'=>'reviewer_required'],403);try{$id=(int)$m[1];$old=PublicReviewAdminService::getSource($pdo,$id);$b=body();$new=PublicReviewAdminService::setPolicy($pdo,$id,(string)($b['access_policy']??'pending_review'),isset($b['access_policy_notes'])?(string)$b['access_policy_notes']:null);Security::audit($pdo,(int)$u['id'],'PRI_SOURCE_POLICY_UPDATE','public_review_source',(string)$id,$old,$new);out(['source'=>$new]);}catch(Throwable $e){out(['error'=>$e->getMessage()],422);}}
if($path==='/api/admin/pri/analyze'&&$method==='POST'){if(!pri_role($u))out(['error'=>'reviewer_required'],403);Security::rateLimit($pdo,'pri-ai-analysis',10,60);$b=body();try{$result=PublicReviewAdminService::analyzeProduct($pdo,(int)($b['product_id']??0),is_array($b['snapshots']??null)?$b['snapshots']:[]);Security::audit($pdo,(int)$u['id'],'PRI_ANALYSIS_RUN','product',(string)($b['product_id']??''),null,['analysis_run_id'=>$result['analysis_run_id'],'eligible'=>$result['eligible'],'excluded'=>$result['excluded'],'intelligence'=>$result['intelligence']]);out($result);}catch(Throwable $e){out(['error'=>$e->getMessage()],422);}}
out(['error'=>'not_found'],404);