<?php
require_once __DIR__.'/../app/lib/Db.php';require_once __DIR__.'/../app/lib/Security.php';require_once __DIR__.'/../app/lib/Entitlements.php';require_once __DIR__.'/../app/lib/Mailer.php';$config=require __DIR__.'/../app/config.php';$pdo=Db::pdo();Security::start();$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
function out($d,int $s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function body(){return json_decode(file_get_contents('php://input'),true)?:[];}function make_token(PDO $pdo,int $uid,string $purpose,int $ttl=86400):string{$raw=bin2hex(random_bytes(32));$pdo->prepare("INSERT INTO auth_tokens(user_id,token_hash,purpose,expires_at) VALUES(?,?,?,?)")->execute([$uid,hash('sha256',$raw,true),$purpose,date('Y-m-d H:i:s',time()+$ttl)]);return $raw;}
if($path==='/api/auth/csrf'&&$method==='GET'){$u=Security::user();out(['csrf_token'=>Security::csrf(),'user'=>$u,'entitlements'=>Entitlements::context($pdo,$u)]);}
if($path==='/api/auth/me'&&$method==='GET'){$u=Security::user();out(['user'=>$u,'entitlements'=>Entitlements::context($pdo,$u)]);}
if($path==='/api/auth/register'&&$method==='POST'){Security::sameOrigin($config);Security::rateLimit($pdo,'register',8,300);$b=body();$email=strtolower(trim($b['email']??''));$password=(string)($b['password']??'');$name=trim($b['name']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10)out(['error'=>'invalid_registration'],422);$hash=password_hash($password,PASSWORD_DEFAULT);try{$pdo->beginTransaction();$st=$pdo->prepare("INSERT INTO users(email,password_hash,full_name,role,status) VALUES(?,?,?,'user','pending')");$st->execute([$email,$hash,$name?:'TechSelectAI User']);$uid=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO user_plan_assignments(user_id,plan_code,plan_status,source) VALUES(?,'free_registered','active','registration')")->execute([$uid]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();out(['error'=>'account_unavailable'],409);} $raw=make_token($pdo,$uid,'verify_email');$url=rtrim($config['site_url'],'/').'/verify-email?token='.$raw;$sent=Mailer::send($config,$email,'Verify your TechSelectAI email',"Verify your email:\n{$url}\n\nThis link expires in 24 hours.");Security::audit($pdo,$uid,'REGISTER','user',(string)$uid);out(['created'=>true,'verification_email_sent'=>$sent],201);}
if($path==='/api/auth/verify'&&$method==='POST'){Security::sameOrigin($config);Security::rateLimit($pdo,'verify',20,300);$raw=(string)(body()['token']??'');$st=$pdo->prepare("SELECT * FROM auth_tokens WHERE token_hash=? AND purpose='verify_email' AND used_at IS NULL AND expires_at>NOW() LIMIT 1");$st->execute([hash('sha256',$raw,true)]);$t=$st->fetch();if(!$t)out(['error'=>'invalid_or_expired_token'],422);$pdo->beginTransaction();$pdo->prepare("UPDATE auth_tokens SET used_at=NOW() WHERE id=?")->execute([$t['id']]);$pdo->prepare("UPDATE users SET status='active',email_verified_at=NOW() WHERE id=?")->execute([$t['user_id']]);$pdo->commit();out(['verified'=>true]);}
if($path==='/api/auth/login'&&$method==='POST'){Security::sameOrigin($config);Security::rateLimit($pdo,'login',12,300);$b=body();$email=strtolower(trim($b['email']??''));$st=$pdo->prepare("SELECT id,email,password_hash,full_name,role,status FROM users WHERE email=? LIMIT 1");$st->execute([$email]);$u=$st->fetch();if(!$u||!password_verify((string)($b['password']??''),$u['password_hash']))out(['error'=>'invalid_credentials'],401);if($u['status']!=='active')out(['error'=>'email_verification_required'],403);session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'email'=>$u['email'],'name'=>$u['full_name'],'role'=>$u['role']];$pdo->prepare("UPDATE users SET last_login_at=NOW() WHERE id=?")->execute([$u['id']]);Security::audit($pdo,(int)$u['id'],'LOGIN','user',(string)$u['id']);out(['user'=>$_SESSION['user'],'entitlements'=>Entitlements::context($pdo,$_SESSION['user']),'csrf_token'=>Security::csrf()]);}
if($path==='/api/auth/logout'&&$method==='POST'){Security::sameOrigin($config);Security::requireCsrf();$u=Security::user();if($u)Security::audit($pdo,(int)$u['id'],'LOGOUT','user',(string)$u['id']);$_SESSION=[];session_destroy();out(['logged_out'=>true]);}
if($path==='/api/auth/request-reset'&&$method==='POST'){Security::sameOrigin($config);Security::rateLimit($pdo,'reset-request',6,600);$email=strtolower(trim(body()['email']??''));$st=$pdo->prepare("SELECT id,email FROM users WHERE email=? AND status='active' LIMIT 1");$st->execute([$email]);if($u=$st->fetch()){$raw=make_token($pdo,(int)$u['id'],'password_reset',3600);$url=rtrim($config['site_url'],'/').'/reset-password?token='.$raw;Mailer::send($config,$u['email'],'Reset your TechSelectAI password',"Reset your password:\n{$url}\n\nThis link expires in 1 hour.");}out(['accepted'=>true]);}
if($path==='/api/auth/reset'&&$method==='POST'){Security::sameOrigin($config);Security::rateLimit($pdo,'reset',10,300);$b=body();$raw=(string)($b['token']??'');$pw=(string)($b['password']??'');if(strlen($pw)<10)out(['error'=>'weak_password'],422);$st=$pdo->prepare("SELECT * FROM auth_tokens WHERE token_hash=? AND purpose='password_reset' AND used_at IS NULL AND expires_at>NOW() LIMIT 1");$st->execute([hash('sha256',$raw,true)]);$t=$st->fetch();if(!$t)out(['error'=>'invalid_or_expired_token'],422);$pdo->beginTransaction();$pdo->prepare("UPDATE users SET password_hash=? WHERE id=?")->execute([password_hash($pw,PASSWORD_DEFAULT),$t['user_id']]);$pdo->prepare("UPDATE auth_tokens SET used_at=NOW() WHERE id=?")->execute([$t['id']]);$pdo->commit();out(['reset'=>true]);}
out(['error'=>'not_found'],404);