<?php
require_once __DIR__.'/../app/lib/Db.php';
require_once __DIR__.'/../app/lib/Security.php';
require_once __DIR__.'/../app/lib/EvidenceFactExtractor.php';
$config=require __DIR__.'/../app/config.php';
$pdo=Db::pdo();Security::start();$user=Security::requireRole(['admin','super_admin','data_editor']);
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
function er_out($d,int $s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function er_body(){return json_decode(file_get_contents('php://input'),true)?:[];}
function fp(?string $v):?string{return $v===null?null:bin2hex($v);}
if($path==='/api/evidence-refresh/candidates'&&$method==='GET'){
  $status=trim((string)($_GET['status']??'pending_review'));$allowed=['pending_review','no_material_change','rejected','needs_fact_extraction','all'];if(!in_array($status,$allowed,true))er_out(['error'=>'invalid_status'],422);
  $sql="SELECT c.id,c.status,c.detected_at,c.reviewed_at,c.review_notes,c.previous_fingerprint,c.current_fingerprint,c.evidence_source_id,es.source_url,es.source_title,es.source_type,es.checked_at,es.verification_status,p.id product_id,p.name product_name,p.slug product_slug,v.name vendor_name,u.full_name reviewer_name,(SELECT r.change_state FROM evidence_refresh_checks r WHERE r.evidence_source_id=c.evidence_source_id ORDER BY r.id DESC LIMIT 1) latest_refresh_state,(SELECT COUNT(*) FROM evidence_fact_proposals efp WHERE efp.candidate_id=c.id) proposal_count FROM evidence_change_candidates c JOIN evidence_sources es ON es.id=c.evidence_source_id JOIN products p ON p.id=es.product_id LEFT JOIN vendors v ON v.id=p.vendor_id LEFT JOIN users u ON u.id=c.reviewed_by_user_id";
  $params=[];if($status!=='all'){$sql.=' WHERE c.status=?';$params[]=$status;}$sql.=' ORDER BY c.detected_at DESC LIMIT 200';$st=$pdo->prepare($sql);$st->execute($params);$rows=[];foreach($st->fetchAll() as $r){$r['previous_fingerprint']=fp($r['previous_fingerprint']);$r['current_fingerprint']=fp($r['current_fingerprint']);$rows[]=$r;}er_out(['candidates'=>$rows,'csrf_token'=>Security::csrf()]);
}
if(preg_match('#^/api/evidence-refresh/candidates/(\d+)/proposals$#',$path,$m)&&$method==='GET'){
  $id=(int)$m[1];$st=$pdo->prepare("SELECT p.id,p.fact_domain,p.field_key,p.previous_value,p.proposed_value,p.confidence,p.rationale,p.source_excerpt,p.status,p.created_at,p.reviewed_at,p.review_notes,cu.full_name created_by,ru.full_name reviewed_by FROM evidence_fact_proposals p LEFT JOIN users cu ON cu.id=p.created_by_user_id LEFT JOIN users ru ON ru.id=p.reviewed_by_user_id WHERE p.candidate_id=? ORDER BY p.id");$st->execute([$id]);er_out(['proposals'=>$st->fetchAll(),'csrf_token'=>Security::csrf()]);
}
if(preg_match('#^/api/evidence-refresh/candidates/(\d+)/extract$#',$path,$m)&&$method==='POST'){
  Security::sameOrigin($config);Security::rateLimit($pdo,'evidence-fact-extraction',10,600);Security::requireCsrf();$id=(int)$m[1];
  $st=$pdo->prepare('SELECT status FROM evidence_change_candidates WHERE id=? LIMIT 1');$st->execute([$id]);$status=$st->fetchColumn();if($status===false)er_out(['error'=>'candidate_not_found'],404);if($status!=='needs_fact_extraction')er_out(['error'=>'candidate_not_ready'],409);
  try{$proposals=EvidenceFactExtractor::extract($pdo,$config,$id);}catch(Throwable $e){Security::audit($pdo,(int)$user['id'],'EVIDENCE_FACT_EXTRACTION_FAILED','evidence_change_candidate',(string)$id,null,['error'=>substr($e->getMessage(),0,500)]);er_out(['error'=>'extraction_failed'],502);}
  $pdo->beginTransaction();$pdo->prepare("DELETE FROM evidence_fact_proposals WHERE candidate_id=? AND status='proposed'")->execute([$id]);$ins=$pdo->prepare("INSERT INTO evidence_fact_proposals(candidate_id,fact_domain,field_key,previous_value,proposed_value,confidence,rationale,source_excerpt,status,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,'proposed',?)");foreach($proposals as $p)$ins->execute([$id,$p['fact_domain'],$p['field_key'],$p['previous_value']!==''?$p['previous_value']:null,$p['proposed_value'],$p['confidence'],$p['rationale']!==''?$p['rationale']:null,$p['source_excerpt']!==''?$p['source_excerpt']:null,(int)$user['id']]);$pdo->commit();Security::audit($pdo,(int)$user['id'],'EVIDENCE_FACT_EXTRACTION','evidence_change_candidate',(string)$id,null,['proposal_count'=>count($proposals)]);er_out(['generated'=>true,'proposal_count'=>count($proposals)]);
}
if(preg_match('#^/api/evidence-refresh/proposals/(\d+)/disposition$#',$path,$m)&&$method==='PUT'){
  Security::sameOrigin($config);Security::rateLimit($pdo,'evidence-fact-proposal-review',40,300);Security::requireCsrf();$id=(int)$m[1];$b=er_body();$next=(string)($b['status']??'');$notes=trim((string)($b['review_notes']??''));if(!in_array($next,['approved_for_application','rejected'],true)||mb_strlen($notes)>4000)er_out(['error'=>'invalid_disposition'],422);
  $st=$pdo->prepare('SELECT id,status,candidate_id,fact_domain,field_key,previous_value,proposed_value,confidence FROM evidence_fact_proposals WHERE id=? LIMIT 1');$st->execute([$id]);$before=$st->fetch();if(!$before)er_out(['error'=>'proposal_not_found'],404);if($before['status']!=='proposed')er_out(['error'=>'proposal_already_dispositioned'],409);
  $pdo->prepare("UPDATE evidence_fact_proposals SET status=?,reviewed_at=NOW(),reviewed_by_user_id=?,review_notes=? WHERE id=? AND status='proposed'")->execute([$next,(int)$user['id'],$notes!==''?$notes:null,$id]);Security::audit($pdo,(int)$user['id'],'EVIDENCE_FACT_PROPOSAL_DISPOSITION','evidence_fact_proposal',(string)$id,$before,['status'=>$next,'review_notes'=>$notes]);er_out(['updated'=>true,'proposal_id'=>$id,'status'=>$next]);
}
if(preg_match('#^/api/evidence-refresh/candidates/(\d+)/disposition$#',$path,$m)&&$method==='PUT'){
  Security::sameOrigin($config);Security::rateLimit($pdo,'evidence-refresh-review',40,300);Security::requireCsrf();$id=(int)$m[1];$b=er_body();$next=(string)($b['status']??'');$notes=trim((string)($b['review_notes']??''));$allowed=['no_material_change','rejected','needs_fact_extraction'];if(!in_array($next,$allowed,true)||mb_strlen($notes)>4000)er_out(['error'=>'invalid_disposition'],422);
  $st=$pdo->prepare('SELECT id,status,review_notes FROM evidence_change_candidates WHERE id=? LIMIT 1');$st->execute([$id]);$before=$st->fetch();if(!$before)er_out(['error'=>'candidate_not_found'],404);if($before['status']!=='pending_review')er_out(['error'=>'candidate_already_dispositioned'],409);
  $pdo->prepare('UPDATE evidence_change_candidates SET status=?,reviewed_at=NOW(),reviewed_by_user_id=?,review_notes=? WHERE id=? AND status=\'pending_review\'')->execute([$next,(int)$user['id'],$notes!==''?$notes:null,$id]);Security::audit($pdo,(int)$user['id'],'EVIDENCE_REFRESH_DISPOSITION','evidence_change_candidate',(string)$id,$before,['status'=>$next,'review_notes'=>$notes]);er_out(['updated'=>true,'candidate_id'=>$id,'status'=>$next]);
}
er_out(['error'=>'not_found'],404);
