<?php
require_once __DIR__.'/../app/lib/Db.php';require_once __DIR__.'/../app/lib/Security.php';require_once __DIR__.'/../app/lib/ProgrammaticSeoQualityGate.php';
$config=require __DIR__.'/../app/config.php';$pdo=Db::pdo();Security::start();$user=Security::requireRole(['reviewer','admin','super_admin']);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
function sq_out($d,$s=200){http_response_code($s);header('Content-Type: application/json');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function sq_body(){return json_decode(file_get_contents('php://input'),true)?:[];}
if($method!=='GET'){Security::sameOrigin($config);Security::requireCsrf();Security::rateLimit($pdo,'seo-quality-gates',30,60);}
if($path==='/api/seo-quality-gates'&&$method==='GET'){$rows=$pdo->query("SELECT id,page_type,slug,canonical_path,intent_key,title,status,quality_decision,quality_score,gate_reasons_json,canonical_target_path,last_gate_run_at,updated_at FROM seo_generated_pages ORDER BY FIELD(quality_decision,'not_generated','published_noindex','pending','indexable'),updated_at DESC LIMIT 1000")->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r){$r['reasons']=json_decode($r['gate_reasons_json']?:'[]',true)?:[];unset($r['gate_reasons_json']);}$sum=$pdo->query("SELECT COUNT(*) total,SUM(quality_decision='indexable') indexable,SUM(quality_decision='published_noindex') noindex,SUM(quality_decision='not_generated') blocked,SUM(quality_decision='pending') pending FROM seo_generated_pages")->fetch(PDO::FETCH_ASSOC);sq_out(['summary'=>$sum,'pages'=>$rows,'settings'=>ProgrammaticSeoQualityGate::settings($pdo),'csrf_token'=>Security::csrf()]);}
if(preg_match('#^/api/seo-quality-gates/(\d+)/run$#',$path,$m)&&$method==='POST'){try{$r=ProgrammaticSeoQualityGate::run($pdo,(int)$m[1],(int)$user['id']);Security::audit($pdo,(int)$user['id'],'SEO_QUALITY_GATE_RUN','seo_generated_page',$m[1],null,$r);sq_out($r);}catch(Throwable $e){sq_out(['error'=>$e->getMessage()],422);}}
if($path==='/api/seo-quality-gates/run-all'&&$method==='POST'){$ids=$pdo->query("SELECT id FROM seo_generated_pages WHERE status<>'archived'")->fetchAll(PDO::FETCH_COLUMN);$out=[];foreach($ids as $id){try{$out[]=['id'=>(int)$id]+ProgrammaticSeoQualityGate::run($pdo,(int)$id,(int)$user['id']);}catch(Throwable $e){}}Security::audit($pdo,(int)$user['id'],'SEO_QUALITY_GATE_RUN_ALL','seo_generated_page','all',null,['count'=>count($out)]);sq_out(['count'=>count($out),'results'=>$out]);}
sq_out(['error'=>'not_found'],404);
