<?php
require_once __DIR__.'/../app/lib/Db.php';require_once __DIR__.'/../app/lib/Security.php';require_once __DIR__.'/../app/lib/SoftwareManagement.php';
$config=require __DIR__.'/../app/config.php';$pdo=Db::pdo();Security::start();$u=Security::requireRole(['admin','data_editor','reviewer','super_admin']);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
function sm_out($d,int $s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function sm_body(){return json_decode(file_get_contents('php://input'),true)?:[];}function sm_reviewer($u){return in_array($u['role'],['reviewer','admin','super_admin'],true);}
if($method!=='GET'){Security::sameOrigin($config);Security::requireCsrf();Security::rateLimit($pdo,'software-management-write',60,60);}
if($path==='/api/software-management'&&$method==='GET'){sm_out(['products'=>SoftwareManagement::list($pdo,$_GET),'reference'=>SoftwareManagement::referenceData($pdo),'csrf_token'=>Security::csrf()]);}
if(preg_match('#^/api/software-management/(\d+)$#',$path,$m)&&$method==='GET'){$p=SoftwareManagement::detail($pdo,(int)$m[1]);if(!$p)sm_out(['error'=>'not_found'],404);sm_out(['product'=>$p,'reference'=>SoftwareManagement::referenceData($pdo),'csrf_token'=>Security::csrf()]);}
if(preg_match('#^/api/software-management/(\d+)$#',$path,$m)&&$method==='PATCH'){
 $id=(int)$m[1];$q=$pdo->prepare('SELECT * FROM products WHERE id=?');$q->execute([$id]);$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)sm_out(['error'=>'not_found'],404);$b=sm_body();$status=(string)($b['status']??$old['status']);if(!in_array($status,['draft','active','archived'],true))sm_out(['error'=>'invalid_status'],422);if($status==='active'&&!sm_reviewer($u))sm_out(['error'=>'reviewer_required_to_activate'],403);
 $name=trim((string)($b['name']??$old['name']));if($name==='')sm_out(['error'=>'name_required'],422);$desc=(string)($b['short_description']??$old['short_description']);$url=trim((string)($b['website_url']??$old['website_url']));$vendor=array_key_exists('vendor_id',$b)?($b['vendor_id']? (int)$b['vendor_id']:null):$old['vendor_id'];$category=array_key_exists('category_id',$b)?($b['category_id']? (int)$b['category_id']:null):$old['category_id'];
 if($status==='active'){ $tmp=$old;$tmp['vendor_id']=$vendor;$tmp['category_id']=$category;$tmp['website_url']=$url;$tmp['short_description']=$desc;$ready=SoftwareManagement::readiness($pdo,$id,$tmp);if(!$ready['ready'])sm_out(['error'=>'publishing_readiness_failed','readiness'=>$ready],409); }
 $pdo->prepare("UPDATE products SET name=?,short_description=?,website_url=?,vendor_id=?,category_id=?,status=?,last_reviewed_at=CASE WHEN ?='active' THEN NOW() ELSE last_reviewed_at END WHERE id=?")->execute([$name,$desc,$url,$vendor,$category,$status,$status,$id]);$q->execute([$id]);$new=$q->fetch(PDO::FETCH_ASSOC);Security::audit($pdo,(int)$u['id'],'PRODUCT_UPDATE','product',(string)$id,$old,$new);sm_out(['product'=>SoftwareManagement::detail($pdo,$id)]);
}
if($path==='/api/software-management/bulk-status'&&$method==='POST'){$b=sm_body();$ids=array_values(array_unique(array_filter(array_map('intval',(array)($b['product_ids']??[])))));$status=(string)($b['status']??'');if(!$ids||!in_array($status,['draft','archived'],true))sm_out(['error'=>'invalid_bulk_request'],422);if(count($ids)>200)sm_out(['error'=>'too_many_products'],422);$ph=implode(',',array_fill(0,count($ids),'?'));$before=$pdo->prepare("SELECT id,status FROM products WHERE id IN($ph)");$before->execute($ids);$old=$before->fetchAll(PDO::FETCH_ASSOC);$args=array_merge([$status],$ids);$pdo->prepare("UPDATE products SET status=? WHERE id IN($ph)")->execute($args);Security::audit($pdo,(int)$u['id'],'PRODUCT_BULK_STATUS','product',implode(',',$ids),$old,['status'=>$status,'ids'=>$ids]);sm_out(['updated'=>count($ids),'status'=>$status]);}
sm_out(['error'=>'not_found'],404);
