<?php
require_once __DIR__.'/../app/lib/Db.php';require_once __DIR__.'/../app/lib/Security.php';require_once __DIR__.'/../app/lib/SoftwareManagement.php';require_once __DIR__.'/../app/lib/SoftwareLogoManager.php';
$config=require __DIR__.'/../app/config.php';$pdo=Db::pdo();Security::start();$u=Security::requireRole(['admin','data_editor','reviewer','super_admin']);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
function sm_out($d,int $s=200){http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function sm_body(){return json_decode(file_get_contents('php://input'),true)?:[];}function sm_reviewer($u){return in_array($u['role'],['reviewer','admin','super_admin'],true);}function sm_product(PDO $pdo,int $id){$q=$pdo->prepare('SELECT * FROM products WHERE id=?');$q->execute([$id]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
if($method!=='GET'){Security::sameOrigin($config);Security::requireCsrf();Security::rateLimit($pdo,'software-management-write',60,60);}
if($path==='/api/software-management'&&$method==='GET'){sm_out(['products'=>SoftwareManagement::list($pdo,$_GET),'reference'=>SoftwareManagement::referenceData($pdo),'csrf_token'=>Security::csrf()]);}
if(preg_match('#^/api/software-management/(\d+)$#',$path,$m)&&$method==='GET'){$p=SoftwareManagement::detail($pdo,(int)$m[1]);if(!$p)sm_out(['error'=>'not_found'],404);sm_out(['product'=>$p,'reference'=>SoftwareManagement::referenceData($pdo),'csrf_token'=>Security::csrf()]);}
if(preg_match('#^/api/software-management/(\d+)/mobile-access$#',$path,$m)&&$method==='PATCH'){
 $id=(int)$m[1];$p=sm_product($pdo,$id);if(!$p)sm_out(['error'=>'not_found'],404);$b=sm_body();$platform=(string)($b['platform']??'');$support=(string)($b['support_status']??'not_yet_verified');$scope=(string)($b['scope_status']??'not_yet_verified');$etype=(string)($b['evidence_type']??'not_yet_verified');
 if(!in_array($platform,['android','ios','mobile_web'],true))sm_out(['error'=>'invalid_mobile_platform'],422);if(!in_array($support,['supported','not_supported','not_yet_verified'],true))sm_out(['error'=>'invalid_support_status'],422);if(!in_array($scope,['full','limited','role_specific','not_yet_verified'],true))sm_out(['error'=>'invalid_scope_status'],422);if(!in_array($etype,['official_app_store','vendor_documentation','other_first_party','not_yet_verified'],true))sm_out(['error'=>'invalid_evidence_type'],422);
 $eurl=trim((string)($b['evidence_url']??''));$notes=trim((string)($b['scope_notes']??''));$confidence=max(0,min(1,(float)($b['confidence_score']??0)));if($support!=='not_yet_verified'&&$eurl==='')sm_out(['error'=>'evidence_url_required_for_verified_mobile_status'],422);if($eurl!==''&&!filter_var($eurl,FILTER_VALIDATE_URL))sm_out(['error'=>'invalid_evidence_url'],422);if($support==='not_yet_verified'){$etype='not_yet_verified';$confidence=0;$eurl='';$scope='not_yet_verified';}
 $before=SoftwareManagement::mobileAccess($pdo,$id);$pdo->prepare("INSERT INTO product_mobile_access(product_id,platform,support_status,scope_status,scope_notes,evidence_url,evidence_type,confidence_score,last_verified_at) VALUES(?,?,?,?,?,?,?,?,CASE WHEN ?='not_yet_verified' THEN NULL ELSE NOW() END) ON DUPLICATE KEY UPDATE support_status=VALUES(support_status),scope_status=VALUES(scope_status),scope_notes=VALUES(scope_notes),evidence_url=VALUES(evidence_url),evidence_type=VALUES(evidence_type),confidence_score=VALUES(confidence_score),last_verified_at=VALUES(last_verified_at)")->execute([$id,$platform,$support,$scope,$notes?:null,$eurl?:null,$etype,$confidence,$support]);$after=SoftwareManagement::mobileAccess($pdo,$id);Security::audit($pdo,(int)$u['id'],'PRODUCT_MOBILE_ACCESS_UPDATE','product',(string)$id,$before,$after);sm_out(['mobile_access'=>$after,'product'=>SoftwareManagement::detail($pdo,$id)]);
}
if(preg_match('#^/api/software-management/(\d+)/logo-discover$#',$path,$m)&&$method==='POST'){
 $id=(int)$m[1];$p=sm_product($pdo,$id);if(!$p)sm_out(['error'=>'not_found'],404);Security::rateLimit($pdo,'software-logo-discover-'.$id,10,300);
 try{$r=SoftwareLogoManager::discover($p);Security::audit($pdo,(int)$u['id'],'PRODUCT_LOGO_DISCOVER','product',(string)$id,null,['official_website'=>$p['website_url'],'candidate_count'=>count($r['candidates'])]);sm_out($r);}catch(Throwable $e){sm_out(['error'=>$e->getMessage()],422);}
}
if(preg_match('#^/api/software-management/(\d+)/logo-approve$#',$path,$m)&&$method==='POST'){
 if(!sm_reviewer($u))sm_out(['error'=>'reviewer_required_to_approve_logo'],403);$id=(int)$m[1];$p=sm_product($pdo,$id);if(!$p)sm_out(['error'=>'not_found'],404);Security::rateLimit($pdo,'software-logo-approve-'.$id,6,300);$b=sm_body();$source=trim((string)($b['source_url']??''));if($source==='')sm_out(['error'=>'source_url_required'],422);$attribution=trim((string)($b['attribution']??''));if($attribution==='')$attribution=((string)($p['name']??'Software')).' logo — official vendor website';
 try{$cached=SoftwareLogoManager::cache($p,$source);}catch(Throwable $e){sm_out(['error'=>$e->getMessage()],422);}
 $before=['logo_path'=>$p['logo_path']??null,'logo_source_url'=>$p['logo_source_url']??null,'logo_attribution'=>$p['logo_attribution']??null,'logo_last_verified_at'=>$p['logo_last_verified_at']??null];
 $pdo->prepare('UPDATE products SET logo_path=?,logo_source_url=?,logo_attribution=?,logo_last_verified_at=NOW() WHERE id=?')->execute([$cached['logo_path'],$cached['source_url'],$attribution,$id]);$after=['logo_path'=>$cached['logo_path'],'logo_source_url'=>$cached['source_url'],'logo_attribution'=>$attribution,'logo_last_verified_at'=>date('Y-m-d H:i:s')];Security::audit($pdo,(int)$u['id'],'PRODUCT_LOGO_APPROVE','product',(string)$id,$before,$after);sm_out(['cached'=>$cached,'product'=>SoftwareManagement::detail($pdo,$id)]);
}
if(preg_match('#^/api/software-management/(\d+)$#',$path,$m)&&$method==='PATCH'){
 $id=(int)$m[1];$q=$pdo->prepare('SELECT * FROM products WHERE id=?');$q->execute([$id]);$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)sm_out(['error'=>'not_found'],404);$b=sm_body();$status=(string)($b['status']??$old['status']);if(!in_array($status,['draft','active','archived'],true))sm_out(['error'=>'invalid_status'],422);$activating=$status==='active'&&$old['status']!=='active';if($activating&&!sm_reviewer($u))sm_out(['error'=>'reviewer_required_to_activate'],403);
 $name=trim((string)($b['name']??$old['name']));if($name==='')sm_out(['error'=>'name_required'],422);$desc=(string)($b['short_description']??$old['short_description']);$url=trim((string)($b['website_url']??$old['website_url']));$vendor=array_key_exists('vendor_id',$b)?($b['vendor_id']? (int)$b['vendor_id']:null):$old['vendor_id'];$category=array_key_exists('category_id',$b)?($b['category_id']? (int)$b['category_id']:null):$old['category_id'];
 if($activating){$tmp=$old;$tmp['vendor_id']=$vendor;$tmp['category_id']=$category;$tmp['website_url']=$url;$tmp['short_description']=$desc;$ready=SoftwareManagement::readiness($pdo,$id,$tmp);if(!$ready['ready'])sm_out(['error'=>'publishing_readiness_failed','readiness'=>$ready],409);}
 $pdo->prepare("UPDATE products SET name=?,short_description=?,website_url=?,vendor_id=?,category_id=?,status=?,last_reviewed_at=CASE WHEN ?='active' AND status<>'active' THEN NOW() ELSE last_reviewed_at END WHERE id=?")->execute([$name,$desc,$url,$vendor,$category,$status,$status,$id]);$q->execute([$id]);$new=$q->fetch(PDO::FETCH_ASSOC);Security::audit($pdo,(int)$u['id'],'PRODUCT_UPDATE','product',(string)$id,$old,$new);sm_out(['product'=>SoftwareManagement::detail($pdo,$id)]);
}
if($path==='/api/software-management/bulk-status'&&$method==='POST'){$b=sm_body();$ids=array_values(array_unique(array_filter(array_map('intval',(array)($b['product_ids']??[])))));$status=(string)($b['status']??'');if(!$ids||!in_array($status,['draft','archived'],true))sm_out(['error'=>'invalid_bulk_request'],422);if(count($ids)>200)sm_out(['error'=>'too_many_products'],422);$ph=implode(',',array_fill(0,count($ids),'?'));$before=$pdo->prepare("SELECT id,status FROM products WHERE id IN($ph)");$before->execute($ids);$old=$before->fetchAll(PDO::FETCH_ASSOC);$args=array_merge([$status],$ids);$pdo->prepare("UPDATE products SET status=? WHERE id IN($ph)")->execute($args);Security::audit($pdo,(int)$u['id'],'PRODUCT_BULK_STATUS','product',implode(',',$ids),$old,['status'=>$status,'ids'=>$ids]);sm_out(['updated'=>count($ids),'status'=>$status]);}
sm_out(['error'=>'not_found'],404);
